# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.4
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/opt/Xilinx/Vivado_HLS/2016.4/../../Vivado/2016.4/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7vx690tffg1927-2 ../xilinx_com_hls_hls_demo_1_0.zip
