-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dr2_int_cap_12_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    eta1_V : IN STD_LOGIC_VECTOR (8 downto 0);
    phi1_V : IN STD_LOGIC_VECTOR (8 downto 0);
    eta2_V : IN STD_LOGIC_VECTOR (8 downto 0);
    phi2_V : IN STD_LOGIC_VECTOR (8 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of dr2_int_cap_12_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv19_835 : STD_LOGIC_VECTOR (18 downto 0) := "0000000100000110101";
    constant ap_const_lv12_835 : STD_LOGIC_VECTOR (11 downto 0) := "100000110101";

    signal deta_V_fu_38_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal deta_V_reg_104 : STD_LOGIC_VECTOR (8 downto 0);
    signal dphi_V_fu_44_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal dphi_V_reg_109 : STD_LOGIC_VECTOR (8 downto 0);
    signal lhs_V_7_fu_50_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal lhs_V_8_fu_59_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_53_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal r_V_reg_126 : STD_LOGIC_VECTOR (17 downto 0);
    signal grp_fu_62_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal r_V_3_reg_131 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_fu_68_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_reg_136 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_234_fu_72_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_234_reg_141 : STD_LOGIC_VECTOR (11 downto 0);
    signal r_V_4_fu_82_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal r_V_4_reg_146 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_2_fu_88_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_2_reg_151 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_53_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_53_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_62_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_62_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal lhs_V_fu_76_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal rhs_V_4_fu_79_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_s_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_53_ce : STD_LOGIC;
    signal grp_fu_62_ce : STD_LOGIC;

    component mp7wrapped_pfalgobkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;



begin
    mp7wrapped_pfalgobkb_U39 : component mp7wrapped_pfalgobkb
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_53_p0,
        din1 => grp_fu_53_p1,
        ce => grp_fu_53_ce,
        dout => grp_fu_53_p2);

    mp7wrapped_pfalgobkb_U40 : component mp7wrapped_pfalgobkb
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 9,
        din1_WIDTH => 9,
        dout_WIDTH => 18)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_62_p0,
        din1 => grp_fu_62_p1,
        ce => grp_fu_62_ce,
        dout => grp_fu_62_p2);




    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                deta_V_reg_104 <= deta_V_fu_38_p2;
                dphi_V_reg_109 <= dphi_V_fu_44_p2;
                r_V_3_reg_131 <= grp_fu_62_p2;
                r_V_4_reg_146 <= r_V_4_fu_82_p2;
                r_V_reg_126 <= grp_fu_53_p2;
                tmp_234_reg_141 <= tmp_234_fu_72_p1;
                tmp_2_reg_151 <= tmp_2_fu_88_p2;
                tmp_reg_136 <= tmp_fu_68_p1;
            end if;
        end if;
    end process;
    ap_return <= 
        tmp_2_reg_151 when (tmp_s_fu_92_p2(0) = '1') else 
        ap_const_lv12_835;
    deta_V_fu_38_p2 <= std_logic_vector(unsigned(eta1_V) - unsigned(eta2_V));
    dphi_V_fu_44_p2 <= std_logic_vector(unsigned(phi1_V) - unsigned(phi2_V));

    grp_fu_53_ce_assign_proc : process(ap_ce)
    begin
        if (not((ap_const_logic_1 = ap_ce))) then 
            grp_fu_53_ce <= ap_const_logic_0;
        else 
            grp_fu_53_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_53_p0 <= lhs_V_7_fu_50_p1(9 - 1 downto 0);
    grp_fu_53_p1 <= lhs_V_7_fu_50_p1(9 - 1 downto 0);

    grp_fu_62_ce_assign_proc : process(ap_ce)
    begin
        if (not((ap_const_logic_1 = ap_ce))) then 
            grp_fu_62_ce <= ap_const_logic_0;
        else 
            grp_fu_62_ce <= ap_const_logic_1;
        end if; 
    end process;

    grp_fu_62_p0 <= lhs_V_8_fu_59_p1(9 - 1 downto 0);
    grp_fu_62_p1 <= lhs_V_8_fu_59_p1(9 - 1 downto 0);
        lhs_V_7_fu_50_p1 <= std_logic_vector(resize(signed(deta_V_reg_104),18));

        lhs_V_8_fu_59_p1 <= std_logic_vector(resize(signed(dphi_V_reg_109),18));

        lhs_V_fu_76_p1 <= std_logic_vector(resize(signed(r_V_reg_126),19));

    r_V_4_fu_82_p2 <= std_logic_vector(signed(lhs_V_fu_76_p1) + signed(rhs_V_4_fu_79_p1));
        rhs_V_4_fu_79_p1 <= std_logic_vector(resize(signed(r_V_3_reg_131),19));

    tmp_234_fu_72_p1 <= grp_fu_53_p2(12 - 1 downto 0);
    tmp_2_fu_88_p2 <= std_logic_vector(unsigned(tmp_reg_136) + unsigned(tmp_234_reg_141));
    tmp_fu_68_p1 <= grp_fu_62_p2(12 - 1 downto 0);
    tmp_s_fu_92_p2 <= "1" when (signed(r_V_4_reg_146) < signed(ap_const_lv19_835)) else "0";
end behav;
