-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ptsort_hwopt is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    in_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    in_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    in_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    in_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    in_0_hwEta_V_read : IN STD_LOGIC_VECTOR (8 downto 0);
    in_1_hwEta_V_read : IN STD_LOGIC_VECTOR (8 downto 0);
    in_2_hwEta_V_read : IN STD_LOGIC_VECTOR (8 downto 0);
    in_3_hwEta_V_read : IN STD_LOGIC_VECTOR (8 downto 0);
    in_4_hwEta_V_read : IN STD_LOGIC_VECTOR (8 downto 0);
    in_0_hwPhi_V_read : IN STD_LOGIC_VECTOR (8 downto 0);
    in_1_hwPhi_V_read : IN STD_LOGIC_VECTOR (8 downto 0);
    in_2_hwPhi_V_read : IN STD_LOGIC_VECTOR (8 downto 0);
    in_3_hwPhi_V_read : IN STD_LOGIC_VECTOR (8 downto 0);
    in_4_hwPhi_V_read : IN STD_LOGIC_VECTOR (8 downto 0);
    in_0_hwId_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    in_1_hwId_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    in_2_hwId_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    in_3_hwId_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    in_4_hwId_V_read : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of ptsort_hwopt is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal p_read_fu_188_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_read_reg_965 : STD_LOGIC_VECTOR (14 downto 0);
    signal in_4_hwId_V_read_1_reg_971 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_in_4_hwId_V_read_1_reg_971 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_3_hwId_V_read_1_reg_979 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_2_hwId_V_read_1_reg_987 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_1_hwId_V_read_1_reg_994 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_0_hwId_V_read_1_reg_1002 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_4_hwPhi_V_read_1_reg_1008 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_pipeline_reg_pp0_iter1_in_4_hwPhi_V_read_1_reg_1008 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_3_hwPhi_V_read_1_reg_1016 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_2_hwPhi_V_read_1_reg_1024 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_1_hwPhi_V_read_1_reg_1031 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_0_hwPhi_V_read_1_reg_1039 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_4_hwEta_V_read_1_reg_1045 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_pipeline_reg_pp0_iter1_in_4_hwEta_V_read_1_reg_1045 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_3_hwEta_V_read_1_reg_1053 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_2_hwEta_V_read_1_reg_1061 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_1_hwEta_V_read_1_reg_1068 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_0_hwEta_V_read_1_reg_1076 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_4_hwPt_V_read_1_reg_1082 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_pipeline_reg_pp0_iter1_in_4_hwPt_V_read_1_reg_1082 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_3_hwPt_V_read_1_reg_1093 : STD_LOGIC_VECTOR (15 downto 0);
    signal in_2_hwPt_V_read_1_reg_1103 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_36_1_2_fu_207_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_1_2_reg_1111 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwPt_V_load_2_2_1_fu_221_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_2_2_1_reg_1121 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_2_1_s_fu_233_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_hwPt_V_load_2_1_s_reg_1128 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_151_reg_1134 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_152_fu_248_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_152_reg_1142 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_153_reg_1147 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_154_fu_260_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_154_reg_1155 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_155_fu_264_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_155_reg_1160 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_155_reg_1160 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_36_2_1_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_2_1_reg_1165 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwPt_V_load_2_3_fu_281_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_2_3_reg_1175 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_36_2_2_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_2_2_reg_1182 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwPt_V_load_2_3_1_fu_300_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_2_3_1_reg_1192 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_2_2_s_fu_307_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_hwPt_V_load_2_2_s_reg_1199 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_hwId_V_load_s_fu_470_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwId_V_load_s_reg_1205 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwPhi_V_load_s_fu_476_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwPhi_V_load_s_reg_1210 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_s_fu_482_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_s_reg_1215 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwPt_V_load_1_4_fu_488_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_1_4_reg_1220 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwId_V_load_1_4_fu_526_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwId_V_load_1_4_reg_1226 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwPhi_V_load_1_4_fu_534_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwPhi_V_load_1_4_reg_1232 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_1_4_fu_542_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_1_4_reg_1238 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwPt_V_load_2_4_fu_550_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_2_4_reg_1244 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwId_V_load_1_4_1_fu_590_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwId_V_load_1_4_1_reg_1251 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwPhi_V_load_1_4_1_fu_598_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwPhi_V_load_1_4_1_reg_1257 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_1_4_1_fu_606_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_1_4_1_reg_1263 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwPt_V_load_2_4_1_fu_614_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_2_4_1_reg_1269 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwId_V_load_1_3_s_fu_621_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwId_V_load_1_3_s_reg_1276 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwPhi_V_load_1_3_2_fu_628_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwPhi_V_load_1_3_2_reg_1282 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_1_3_2_fu_635_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_1_3_2_reg_1288 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwPt_V_load_2_3_s_fu_642_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_hwPt_V_load_2_3_s_reg_1294 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_enable_reg_pp0_iter0_preg : STD_LOGIC := '0';
    signal ap_port_reg_in_1_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_in_2_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_in_3_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_in_4_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_in_0_hwEta_V_read : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_in_1_hwEta_V_read : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_in_2_hwEta_V_read : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_in_3_hwEta_V_read : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_in_4_hwEta_V_read : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_in_0_hwPhi_V_read : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_in_1_hwPhi_V_read : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_in_2_hwPhi_V_read : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_in_3_hwPhi_V_read : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_in_4_hwPhi_V_read : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_in_0_hwId_V_read : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_in_1_hwId_V_read : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_in_2_hwId_V_read : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_in_3_hwId_V_read : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_in_4_hwId_V_read : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_176_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_148_fu_184_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_read_cast_fu_196_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_149_fu_199_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read1_tmp_hwPt_V_lo_fu_213_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_150_fu_229_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_read2_tmp_hwPt_V_lo_fu_275_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_2_1_1_fu_268_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read2_tmp_hwPt_V_lo_1_fu_293_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read16_read_fu_313_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read11_read_fu_318_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read6_read5_fu_323_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read17_tmp_hwId_V_l_fu_343_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read12_tmp_hwPhi_V_s_fu_349_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read7_tmp_hwEta_V_l_fu_355_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read15_read_fu_328_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read10_read_fu_333_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read5_read6_fu_338_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read17_tmp_hwId_V_l_1_fu_379_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read12_tmp_hwPhi_V_1_fu_385_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read7_tmp_hwEta_V_l_1_fu_391_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_36_3_fu_439_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwId_V_load_1_3_fu_361_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwPhi_V_load_1_3_fu_367_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_1_3_fu_373_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read18_tmp_hwId_V_l_fu_443_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read13_tmp_hwPhi_V_s_fu_450_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read8_tmp_hwEta_V_l_fu_457_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read3_tmp_hwPt_V_lo_fu_464_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_36_3_1_fu_495_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwId_V_load_1_3_1_fu_397_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwPhi_V_load_1_3_1_fu_404_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_1_3_1_fu_411_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read18_tmp_hwId_V_l_1_fu_499_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read13_tmp_hwPhi_V_1_fu_506_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read8_tmp_hwEta_V_l_1_fu_513_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read3_tmp_hwPt_V_lo_1_fu_520_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_2_2_1_17_fu_436_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_36_3_2_fu_557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwId_V_load_1_2_s_fu_418_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_hwPhi_V_load_1_2_fu_424_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_hwEta_V_load_1_2_fu_430_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read18_tmp_hwId_V_l_2_fu_562_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read13_tmp_hwPhi_V_2_fu_569_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read8_tmp_hwEta_V_l_2_fu_576_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read3_tmp_hwPt_V_lo_2_fu_583_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_36_4_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_4_fu_651_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read19_tmp_hwId_V_l_fu_659_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_3_hwId_V_write_s_fu_683_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read14_tmp_hwPhi_V_s_fu_665_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read9_tmp_hwEta_V_l_fu_671_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read4_tmp_hwPt_V_lo_fu_677_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_36_4_1_fu_715_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read19_tmp_hwId_V_l_1_fu_719_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_2_hwId_V_write_s_fu_743_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read14_tmp_hwPhi_V_1_fu_725_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read9_tmp_hwEta_V_l_1_fu_731_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read4_tmp_hwPt_V_lo_1_fu_737_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_hwPt_V_load_2_3_1_18_fu_648_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_36_4_2_fu_775_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read19_tmp_hwId_V_l_2_fu_780_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_1_hwId_V_write_s_fu_805_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_read14_tmp_hwPhi_V_2_fu_786_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read9_tmp_hwEta_V_l_2_fu_792_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_read4_tmp_hwPt_V_lo_2_fu_798_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_0_hwId_V_write_s_fu_837_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_0_hwPt_V_write_s_fu_859_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal out_0_hwPt_V_write_1_fu_865_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_1_hwPt_V_write_s_fu_830_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_2_hwPt_V_write_s_fu_768_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_3_hwPt_V_write_s_fu_708_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_0_hwEta_V_write_fu_853_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_1_hwEta_V_write_fu_823_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_2_hwEta_V_write_fu_761_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_3_hwEta_V_write_fu_701_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_0_hwPhi_V_write_fu_847_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_1_hwPhi_V_write_fu_816_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_2_hwPhi_V_write_fu_754_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_3_hwPhi_V_write_fu_694_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_0_hwId_V_write_1_fu_843_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_1_hwId_V_write_1_fu_812_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_2_hwId_V_write_1_fu_750_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal out_3_hwId_V_write_1_fu_690_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_pipeline_idle_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_preg <= ap_const_logic_0;
            else
                if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then 
                    ap_enable_reg_pp0_iter0_preg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter1)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1))) then
                ap_pipeline_reg_pp0_iter1_in_4_hwEta_V_read_1_reg_1045 <= in_4_hwEta_V_read_1_reg_1045;
                ap_pipeline_reg_pp0_iter1_in_4_hwId_V_read_1_reg_971 <= in_4_hwId_V_read_1_reg_971;
                ap_pipeline_reg_pp0_iter1_in_4_hwPhi_V_read_1_reg_1008 <= in_4_hwPhi_V_read_1_reg_1008;
                ap_pipeline_reg_pp0_iter1_in_4_hwPt_V_read_1_reg_1082 <= in_4_hwPt_V_read_1_reg_1082;
                ap_pipeline_reg_pp0_iter1_tmp_155_reg_1160 <= tmp_155_reg_1160;
                in_0_hwEta_V_read_1_reg_1076 <= ap_port_reg_in_0_hwEta_V_read;
                in_0_hwId_V_read_1_reg_1002 <= ap_port_reg_in_0_hwId_V_read;
                in_0_hwPhi_V_read_1_reg_1039 <= ap_port_reg_in_0_hwPhi_V_read;
                in_1_hwEta_V_read_1_reg_1068 <= ap_port_reg_in_1_hwEta_V_read;
                in_1_hwId_V_read_1_reg_994 <= ap_port_reg_in_1_hwId_V_read;
                in_1_hwPhi_V_read_1_reg_1031 <= ap_port_reg_in_1_hwPhi_V_read;
                in_2_hwEta_V_read_1_reg_1061 <= ap_port_reg_in_2_hwEta_V_read;
                in_2_hwId_V_read_1_reg_987 <= ap_port_reg_in_2_hwId_V_read;
                in_2_hwPhi_V_read_1_reg_1024 <= ap_port_reg_in_2_hwPhi_V_read;
                in_2_hwPt_V_read_1_reg_1103 <= ap_port_reg_in_2_hwPt_V_read;
                in_3_hwEta_V_read_1_reg_1053 <= ap_port_reg_in_3_hwEta_V_read;
                in_3_hwId_V_read_1_reg_979 <= ap_port_reg_in_3_hwId_V_read;
                in_3_hwPhi_V_read_1_reg_1016 <= ap_port_reg_in_3_hwPhi_V_read;
                in_3_hwPt_V_read_1_reg_1093 <= ap_port_reg_in_3_hwPt_V_read;
                in_4_hwEta_V_read_1_reg_1045 <= ap_port_reg_in_4_hwEta_V_read;
                in_4_hwId_V_read_1_reg_971 <= ap_port_reg_in_4_hwId_V_read;
                in_4_hwPhi_V_read_1_reg_1008 <= ap_port_reg_in_4_hwPhi_V_read;
                in_4_hwPt_V_read_1_reg_1082 <= ap_port_reg_in_4_hwPt_V_read;
                tmp_151_reg_1134 <= ap_port_reg_in_2_hwPt_V_read(15 downto 15);
                tmp_152_reg_1142 <= tmp_152_fu_248_p1;
                tmp_153_reg_1147 <= ap_port_reg_in_3_hwPt_V_read(15 downto 15);
                tmp_154_reg_1155 <= tmp_154_fu_260_p1;
                tmp_155_reg_1160 <= tmp_155_fu_264_p1;
                tmp_36_1_2_reg_1111 <= tmp_36_1_2_fu_207_p2;
                tmp_hwEta_V_load_1_3_2_reg_1288 <= tmp_hwEta_V_load_1_3_2_fu_635_p3;
                tmp_hwEta_V_load_1_4_1_reg_1263 <= tmp_hwEta_V_load_1_4_1_fu_606_p3;
                tmp_hwEta_V_load_1_4_reg_1238 <= tmp_hwEta_V_load_1_4_fu_542_p3;
                tmp_hwEta_V_load_s_reg_1215 <= tmp_hwEta_V_load_s_fu_482_p3;
                tmp_hwId_V_load_1_3_s_reg_1276 <= tmp_hwId_V_load_1_3_s_fu_621_p3;
                tmp_hwId_V_load_1_4_1_reg_1251 <= tmp_hwId_V_load_1_4_1_fu_590_p3;
                tmp_hwId_V_load_1_4_reg_1226 <= tmp_hwId_V_load_1_4_fu_526_p3;
                tmp_hwId_V_load_s_reg_1205 <= tmp_hwId_V_load_s_fu_470_p3;
                tmp_hwPhi_V_load_1_3_2_reg_1282 <= tmp_hwPhi_V_load_1_3_2_fu_628_p3;
                tmp_hwPhi_V_load_1_4_1_reg_1257 <= tmp_hwPhi_V_load_1_4_1_fu_598_p3;
                tmp_hwPhi_V_load_1_4_reg_1232 <= tmp_hwPhi_V_load_1_4_fu_534_p3;
                tmp_hwPhi_V_load_s_reg_1210 <= tmp_hwPhi_V_load_s_fu_476_p3;
                tmp_hwPt_V_load_1_4_reg_1220 <= tmp_hwPt_V_load_1_4_fu_488_p3;
                tmp_hwPt_V_load_2_1_s_reg_1128 <= tmp_hwPt_V_load_2_1_s_fu_233_p3;
                tmp_hwPt_V_load_2_2_1_reg_1121 <= tmp_hwPt_V_load_2_2_1_fu_221_p3;
                tmp_hwPt_V_load_2_3_s_reg_1294 <= tmp_hwPt_V_load_2_3_s_fu_642_p3;
                tmp_hwPt_V_load_2_4_1_reg_1269 <= tmp_hwPt_V_load_2_4_1_fu_614_p3;
                tmp_hwPt_V_load_2_4_reg_1244 <= tmp_hwPt_V_load_2_4_fu_550_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then
                ap_port_reg_in_0_hwEta_V_read <= in_0_hwEta_V_read;
                ap_port_reg_in_0_hwId_V_read <= in_0_hwId_V_read;
                ap_port_reg_in_0_hwPhi_V_read <= in_0_hwPhi_V_read;
                ap_port_reg_in_1_hwEta_V_read <= in_1_hwEta_V_read;
                ap_port_reg_in_1_hwId_V_read <= in_1_hwId_V_read;
                ap_port_reg_in_1_hwPhi_V_read <= in_1_hwPhi_V_read;
                ap_port_reg_in_1_hwPt_V_read <= in_1_hwPt_V_read;
                ap_port_reg_in_2_hwEta_V_read <= in_2_hwEta_V_read;
                ap_port_reg_in_2_hwId_V_read <= in_2_hwId_V_read;
                ap_port_reg_in_2_hwPhi_V_read <= in_2_hwPhi_V_read;
                ap_port_reg_in_2_hwPt_V_read <= in_2_hwPt_V_read;
                ap_port_reg_in_3_hwEta_V_read <= in_3_hwEta_V_read;
                ap_port_reg_in_3_hwId_V_read <= in_3_hwId_V_read;
                ap_port_reg_in_3_hwPhi_V_read <= in_3_hwPhi_V_read;
                ap_port_reg_in_3_hwPt_V_read <= in_3_hwPt_V_read;
                ap_port_reg_in_4_hwEta_V_read <= in_4_hwEta_V_read;
                ap_port_reg_in_4_hwId_V_read <= in_4_hwId_V_read;
                ap_port_reg_in_4_hwPhi_V_read <= in_4_hwPhi_V_read;
                ap_port_reg_in_4_hwPt_V_read <= in_4_hwPt_V_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then
                p_read_reg_965 <= p_read_fu_188_p3;
                tmp_36_2_1_reg_1165 <= tmp_36_2_1_fu_271_p2;
                tmp_36_2_2_reg_1182 <= tmp_36_2_2_fu_288_p2;
                tmp_hwPt_V_load_2_2_s_reg_1199 <= tmp_hwPt_V_load_2_2_s_fu_307_p3;
                tmp_hwPt_V_load_2_3_1_reg_1192 <= tmp_hwPt_V_load_2_3_1_fu_300_p3;
                tmp_hwPt_V_load_2_3_reg_1175 <= tmp_hwPt_V_load_2_3_fu_281_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_pipeline_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_const_logic_1 = ap_pipeline_idle_pp0)) and not(((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_pipeline_idle_pp0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1 downto 1);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0)) or ((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_preg)
    begin
        if ((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_preg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_pipeline_idle_pp0_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1))) then 
            ap_pipeline_idle_pp0 <= ap_const_logic_1;
        else 
            ap_pipeline_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= out_0_hwPt_V_write_1_fu_865_p1;
    ap_return_1 <= out_1_hwPt_V_write_s_fu_830_p3;
    ap_return_10 <= out_2_hwPhi_V_write_fu_754_p3;
    ap_return_11 <= out_3_hwPhi_V_write_fu_694_p3;
    ap_return_12 <= out_0_hwId_V_write_1_fu_843_p1;
    ap_return_13 <= out_1_hwId_V_write_1_fu_812_p1;
    ap_return_14 <= out_2_hwId_V_write_1_fu_750_p1;
    ap_return_15 <= out_3_hwId_V_write_1_fu_690_p1;
    ap_return_2 <= out_2_hwPt_V_write_s_fu_768_p3;
    ap_return_3 <= out_3_hwPt_V_write_s_fu_708_p3;
    ap_return_4 <= out_0_hwEta_V_write_fu_853_p3;
    ap_return_5 <= out_1_hwEta_V_write_fu_823_p3;
    ap_return_6 <= out_2_hwEta_V_write_fu_761_p3;
    ap_return_7 <= out_3_hwEta_V_write_fu_701_p3;
    ap_return_8 <= out_0_hwPhi_V_write_fu_847_p3;
    ap_return_9 <= out_1_hwPhi_V_write_fu_816_p3;
    out_0_hwEta_V_write_fu_853_p3 <= 
        tmp_hwEta_V_load_1_3_2_reg_1288 when (tmp_36_4_2_fu_775_p2(0) = '1') else 
        ap_pipeline_reg_pp0_iter1_in_4_hwEta_V_read_1_reg_1045;
    out_0_hwId_V_write_1_fu_843_p1 <= std_logic_vector(resize(unsigned(out_0_hwId_V_write_s_fu_837_p3),3));
    out_0_hwId_V_write_s_fu_837_p3 <= 
        tmp_hwId_V_load_1_3_s_reg_1276 when (tmp_36_4_2_fu_775_p2(0) = '1') else 
        ap_pipeline_reg_pp0_iter1_in_4_hwId_V_read_1_reg_971;
    out_0_hwPhi_V_write_fu_847_p3 <= 
        tmp_hwPhi_V_load_1_3_2_reg_1282 when (tmp_36_4_2_fu_775_p2(0) = '1') else 
        ap_pipeline_reg_pp0_iter1_in_4_hwPhi_V_read_1_reg_1008;
    out_0_hwPt_V_write_1_fu_865_p1 <= std_logic_vector(resize(unsigned(out_0_hwPt_V_write_s_fu_859_p3),16));
    out_0_hwPt_V_write_s_fu_859_p3 <= 
        tmp_hwPt_V_load_2_3_s_reg_1294 when (tmp_36_4_2_fu_775_p2(0) = '1') else 
        ap_pipeline_reg_pp0_iter1_tmp_155_reg_1160;
    out_1_hwEta_V_write_fu_823_p3 <= 
        tmp_hwEta_V_load_1_4_1_reg_1263 when (tmp_36_4_1_fu_715_p2(0) = '1') else 
        p_read9_tmp_hwEta_V_l_2_fu_792_p3;
    out_1_hwId_V_write_1_fu_812_p1 <= std_logic_vector(resize(unsigned(out_1_hwId_V_write_s_fu_805_p3),3));
    out_1_hwId_V_write_s_fu_805_p3 <= 
        tmp_hwId_V_load_1_4_1_reg_1251 when (tmp_36_4_1_fu_715_p2(0) = '1') else 
        p_read19_tmp_hwId_V_l_2_fu_780_p3;
    out_1_hwPhi_V_write_fu_816_p3 <= 
        tmp_hwPhi_V_load_1_4_1_reg_1257 when (tmp_36_4_1_fu_715_p2(0) = '1') else 
        p_read14_tmp_hwPhi_V_2_fu_786_p3;
    out_1_hwPt_V_write_s_fu_830_p3 <= 
        tmp_hwPt_V_load_2_4_1_reg_1269 when (tmp_36_4_1_fu_715_p2(0) = '1') else 
        p_read4_tmp_hwPt_V_lo_2_fu_798_p3;
    out_2_hwEta_V_write_fu_761_p3 <= 
        tmp_hwEta_V_load_1_4_reg_1238 when (tmp_36_4_fu_655_p2(0) = '1') else 
        p_read9_tmp_hwEta_V_l_1_fu_731_p3;
    out_2_hwId_V_write_1_fu_750_p1 <= std_logic_vector(resize(unsigned(out_2_hwId_V_write_s_fu_743_p3),3));
    out_2_hwId_V_write_s_fu_743_p3 <= 
        tmp_hwId_V_load_1_4_reg_1226 when (tmp_36_4_fu_655_p2(0) = '1') else 
        p_read19_tmp_hwId_V_l_1_fu_719_p3;
    out_2_hwPhi_V_write_fu_754_p3 <= 
        tmp_hwPhi_V_load_1_4_reg_1232 when (tmp_36_4_fu_655_p2(0) = '1') else 
        p_read14_tmp_hwPhi_V_1_fu_725_p3;
    out_2_hwPt_V_write_s_fu_768_p3 <= 
        tmp_hwPt_V_load_2_4_reg_1244 when (tmp_36_4_fu_655_p2(0) = '1') else 
        p_read4_tmp_hwPt_V_lo_1_fu_737_p3;
    out_3_hwEta_V_write_fu_701_p3 <= 
        tmp_hwEta_V_load_s_reg_1215 when (tmp_32_4_fu_651_p2(0) = '1') else 
        p_read9_tmp_hwEta_V_l_fu_671_p3;
    out_3_hwId_V_write_1_fu_690_p1 <= std_logic_vector(resize(unsigned(out_3_hwId_V_write_s_fu_683_p3),3));
    out_3_hwId_V_write_s_fu_683_p3 <= 
        tmp_hwId_V_load_s_reg_1205 when (tmp_32_4_fu_651_p2(0) = '1') else 
        p_read19_tmp_hwId_V_l_fu_659_p3;
    out_3_hwPhi_V_write_fu_694_p3 <= 
        tmp_hwPhi_V_load_s_reg_1210 when (tmp_32_4_fu_651_p2(0) = '1') else 
        p_read14_tmp_hwPhi_V_s_fu_665_p3;
    out_3_hwPt_V_write_s_fu_708_p3 <= 
        tmp_hwPt_V_load_1_4_reg_1220 when (tmp_32_4_fu_651_p2(0) = '1') else 
        p_read4_tmp_hwPt_V_lo_fu_677_p3;
    p_read10_read_fu_333_p3 <= 
        in_0_hwPhi_V_read_1_reg_1039 when (tmp_36_1_2_reg_1111(0) = '1') else 
        in_1_hwPhi_V_read_1_reg_1031;
    p_read11_read_fu_318_p3 <= 
        in_1_hwPhi_V_read_1_reg_1031 when (tmp_36_1_2_reg_1111(0) = '1') else 
        in_0_hwPhi_V_read_1_reg_1039;
    p_read12_tmp_hwPhi_V_1_fu_385_p3 <= 
        in_2_hwPhi_V_read_1_reg_1024 when (tmp_36_2_2_reg_1182(0) = '1') else 
        p_read10_read_fu_333_p3;
    p_read12_tmp_hwPhi_V_s_fu_349_p3 <= 
        in_2_hwPhi_V_read_1_reg_1024 when (tmp_36_2_1_reg_1165(0) = '1') else 
        p_read11_read_fu_318_p3;
    p_read13_tmp_hwPhi_V_1_fu_506_p3 <= 
        in_3_hwPhi_V_read_1_reg_1016 when (tmp_36_3_1_fu_495_p2(0) = '1') else 
        tmp_hwPhi_V_load_1_3_1_fu_404_p3;
    p_read13_tmp_hwPhi_V_2_fu_569_p3 <= 
        in_3_hwPhi_V_read_1_reg_1016 when (tmp_36_3_2_fu_557_p2(0) = '1') else 
        tmp_hwPhi_V_load_1_2_fu_424_p3;
    p_read13_tmp_hwPhi_V_s_fu_450_p3 <= 
        in_3_hwPhi_V_read_1_reg_1016 when (tmp_36_3_fu_439_p2(0) = '1') else 
        tmp_hwPhi_V_load_1_3_fu_367_p3;
    p_read14_tmp_hwPhi_V_1_fu_725_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwPhi_V_read_1_reg_1008 when (tmp_36_4_1_fu_715_p2(0) = '1') else 
        tmp_hwPhi_V_load_1_4_1_reg_1257;
    p_read14_tmp_hwPhi_V_2_fu_786_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwPhi_V_read_1_reg_1008 when (tmp_36_4_2_fu_775_p2(0) = '1') else 
        tmp_hwPhi_V_load_1_3_2_reg_1282;
    p_read14_tmp_hwPhi_V_s_fu_665_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwPhi_V_read_1_reg_1008 when (tmp_36_4_fu_655_p2(0) = '1') else 
        tmp_hwPhi_V_load_1_4_reg_1232;
    p_read15_read_fu_328_p3 <= 
        in_0_hwId_V_read_1_reg_1002 when (tmp_36_1_2_reg_1111(0) = '1') else 
        in_1_hwId_V_read_1_reg_994;
    p_read16_read_fu_313_p3 <= 
        in_1_hwId_V_read_1_reg_994 when (tmp_36_1_2_reg_1111(0) = '1') else 
        in_0_hwId_V_read_1_reg_1002;
    p_read17_tmp_hwId_V_l_1_fu_379_p3 <= 
        in_2_hwId_V_read_1_reg_987 when (tmp_36_2_2_reg_1182(0) = '1') else 
        p_read15_read_fu_328_p3;
    p_read17_tmp_hwId_V_l_fu_343_p3 <= 
        in_2_hwId_V_read_1_reg_987 when (tmp_36_2_1_reg_1165(0) = '1') else 
        p_read16_read_fu_313_p3;
    p_read18_tmp_hwId_V_l_1_fu_499_p3 <= 
        in_3_hwId_V_read_1_reg_979 when (tmp_36_3_1_fu_495_p2(0) = '1') else 
        tmp_hwId_V_load_1_3_1_fu_397_p3;
    p_read18_tmp_hwId_V_l_2_fu_562_p3 <= 
        in_3_hwId_V_read_1_reg_979 when (tmp_36_3_2_fu_557_p2(0) = '1') else 
        tmp_hwId_V_load_1_2_s_fu_418_p3;
    p_read18_tmp_hwId_V_l_fu_443_p3 <= 
        in_3_hwId_V_read_1_reg_979 when (tmp_36_3_fu_439_p2(0) = '1') else 
        tmp_hwId_V_load_1_3_fu_361_p3;
    p_read19_tmp_hwId_V_l_1_fu_719_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwId_V_read_1_reg_971 when (tmp_36_4_1_fu_715_p2(0) = '1') else 
        tmp_hwId_V_load_1_4_1_reg_1251;
    p_read19_tmp_hwId_V_l_2_fu_780_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwId_V_read_1_reg_971 when (tmp_36_4_2_fu_775_p2(0) = '1') else 
        tmp_hwId_V_load_1_3_s_reg_1276;
    p_read19_tmp_hwId_V_l_fu_659_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwId_V_read_1_reg_971 when (tmp_36_4_fu_655_p2(0) = '1') else 
        tmp_hwId_V_load_1_4_reg_1226;
    p_read1_tmp_hwPt_V_lo_fu_213_p3 <= 
        ap_port_reg_in_1_hwPt_V_read when (tmp_36_1_2_fu_207_p2(0) = '1') else 
        p_read_cast_fu_196_p1;
    p_read2_tmp_hwPt_V_lo_1_fu_293_p3 <= 
        in_2_hwPt_V_read_1_reg_1103 when (tmp_36_2_2_fu_288_p2(0) = '1') else 
        tmp_hwPt_V_load_2_1_1_fu_268_p1;
    p_read2_tmp_hwPt_V_lo_fu_275_p3 <= 
        in_2_hwPt_V_read_1_reg_1103 when (tmp_36_2_1_fu_271_p2(0) = '1') else 
        tmp_hwPt_V_load_2_2_1_reg_1121;
    p_read3_tmp_hwPt_V_lo_1_fu_520_p3 <= 
        in_3_hwPt_V_read_1_reg_1093 when (tmp_36_3_1_fu_495_p2(0) = '1') else 
        tmp_hwPt_V_load_2_3_1_reg_1192;
    p_read3_tmp_hwPt_V_lo_2_fu_583_p3 <= 
        in_3_hwPt_V_read_1_reg_1093 when (tmp_36_3_2_fu_557_p2(0) = '1') else 
        tmp_hwPt_V_load_2_2_1_17_fu_436_p1;
    p_read3_tmp_hwPt_V_lo_fu_464_p3 <= 
        in_3_hwPt_V_read_1_reg_1093 when (tmp_36_3_fu_439_p2(0) = '1') else 
        tmp_hwPt_V_load_2_3_reg_1175;
    p_read4_tmp_hwPt_V_lo_1_fu_737_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwPt_V_read_1_reg_1082 when (tmp_36_4_1_fu_715_p2(0) = '1') else 
        tmp_hwPt_V_load_2_4_1_reg_1269;
    p_read4_tmp_hwPt_V_lo_2_fu_798_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwPt_V_read_1_reg_1082 when (tmp_36_4_2_fu_775_p2(0) = '1') else 
        tmp_hwPt_V_load_2_3_1_18_fu_648_p1;
    p_read4_tmp_hwPt_V_lo_fu_677_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwPt_V_read_1_reg_1082 when (tmp_36_4_fu_655_p2(0) = '1') else 
        tmp_hwPt_V_load_2_4_reg_1244;
    p_read5_read6_fu_338_p3 <= 
        in_0_hwEta_V_read_1_reg_1076 when (tmp_36_1_2_reg_1111(0) = '1') else 
        in_1_hwEta_V_read_1_reg_1068;
    p_read6_read5_fu_323_p3 <= 
        in_1_hwEta_V_read_1_reg_1068 when (tmp_36_1_2_reg_1111(0) = '1') else 
        in_0_hwEta_V_read_1_reg_1076;
    p_read7_tmp_hwEta_V_l_1_fu_391_p3 <= 
        in_2_hwEta_V_read_1_reg_1061 when (tmp_36_2_2_reg_1182(0) = '1') else 
        p_read5_read6_fu_338_p3;
    p_read7_tmp_hwEta_V_l_fu_355_p3 <= 
        in_2_hwEta_V_read_1_reg_1061 when (tmp_36_2_1_reg_1165(0) = '1') else 
        p_read6_read5_fu_323_p3;
    p_read8_tmp_hwEta_V_l_1_fu_513_p3 <= 
        in_3_hwEta_V_read_1_reg_1053 when (tmp_36_3_1_fu_495_p2(0) = '1') else 
        tmp_hwEta_V_load_1_3_1_fu_411_p3;
    p_read8_tmp_hwEta_V_l_2_fu_576_p3 <= 
        in_3_hwEta_V_read_1_reg_1053 when (tmp_36_3_2_fu_557_p2(0) = '1') else 
        tmp_hwEta_V_load_1_2_fu_430_p3;
    p_read8_tmp_hwEta_V_l_fu_457_p3 <= 
        in_3_hwEta_V_read_1_reg_1053 when (tmp_36_3_fu_439_p2(0) = '1') else 
        tmp_hwEta_V_load_1_3_fu_373_p3;
    p_read9_tmp_hwEta_V_l_1_fu_731_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwEta_V_read_1_reg_1045 when (tmp_36_4_1_fu_715_p2(0) = '1') else 
        tmp_hwEta_V_load_1_4_1_reg_1263;
    p_read9_tmp_hwEta_V_l_2_fu_792_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwEta_V_read_1_reg_1045 when (tmp_36_4_2_fu_775_p2(0) = '1') else 
        tmp_hwEta_V_load_1_3_2_reg_1288;
    p_read9_tmp_hwEta_V_l_fu_671_p3 <= 
        ap_pipeline_reg_pp0_iter1_in_4_hwEta_V_read_1_reg_1045 when (tmp_36_4_fu_655_p2(0) = '1') else 
        tmp_hwEta_V_load_1_4_reg_1238;
    p_read_cast_fu_196_p1 <= std_logic_vector(resize(unsigned(p_read_reg_965),16));
    p_read_fu_188_p3 <= 
        ap_const_lv15_0 when (tmp_fu_176_p3(0) = '1') else 
        tmp_148_fu_184_p1;
    tmp_148_fu_184_p1 <= in_0_hwPt_V_read(15 - 1 downto 0);
    tmp_149_fu_199_p3 <= ap_port_reg_in_1_hwPt_V_read(15 downto 15);
    tmp_150_fu_229_p1 <= ap_port_reg_in_1_hwPt_V_read(15 - 1 downto 0);
    tmp_152_fu_248_p1 <= ap_port_reg_in_2_hwPt_V_read(15 - 1 downto 0);
    tmp_154_fu_260_p1 <= ap_port_reg_in_3_hwPt_V_read(15 - 1 downto 0);
    tmp_155_fu_264_p1 <= ap_port_reg_in_4_hwPt_V_read(15 - 1 downto 0);
    tmp_32_4_fu_651_p2 <= "1" when (signed(tmp_hwPt_V_load_1_4_reg_1220) > signed(ap_pipeline_reg_pp0_iter1_in_4_hwPt_V_read_1_reg_1082)) else "0";
    tmp_36_1_2_fu_207_p2 <= "1" when (signed(p_read_cast_fu_196_p1) > signed(ap_port_reg_in_1_hwPt_V_read)) else "0";
    tmp_36_2_1_fu_271_p2 <= "1" when (signed(tmp_hwPt_V_load_2_2_1_reg_1121) > signed(in_2_hwPt_V_read_1_reg_1103)) else "0";
    tmp_36_2_2_fu_288_p2 <= "1" when (signed(tmp_hwPt_V_load_2_1_1_fu_268_p1) > signed(in_2_hwPt_V_read_1_reg_1103)) else "0";
    tmp_36_3_1_fu_495_p2 <= "1" when (signed(tmp_hwPt_V_load_2_3_1_reg_1192) > signed(in_3_hwPt_V_read_1_reg_1093)) else "0";
    tmp_36_3_2_fu_557_p2 <= "1" when (signed(tmp_hwPt_V_load_2_2_1_17_fu_436_p1) > signed(in_3_hwPt_V_read_1_reg_1093)) else "0";
    tmp_36_3_fu_439_p2 <= "1" when (signed(tmp_hwPt_V_load_2_3_reg_1175) > signed(in_3_hwPt_V_read_1_reg_1093)) else "0";
    tmp_36_4_1_fu_715_p2 <= "1" when (signed(tmp_hwPt_V_load_2_4_1_reg_1269) > signed(ap_pipeline_reg_pp0_iter1_in_4_hwPt_V_read_1_reg_1082)) else "0";
    tmp_36_4_2_fu_775_p2 <= "1" when (signed(tmp_hwPt_V_load_2_3_1_18_fu_648_p1) > signed(ap_pipeline_reg_pp0_iter1_in_4_hwPt_V_read_1_reg_1082)) else "0";
    tmp_36_4_fu_655_p2 <= "1" when (signed(tmp_hwPt_V_load_2_4_reg_1244) > signed(ap_pipeline_reg_pp0_iter1_in_4_hwPt_V_read_1_reg_1082)) else "0";
    tmp_fu_176_p3 <= in_0_hwPt_V_read(15 downto 15);
    tmp_hwEta_V_load_1_2_fu_430_p3 <= 
        p_read5_read6_fu_338_p3 when (tmp_36_2_2_reg_1182(0) = '1') else 
        in_2_hwEta_V_read_1_reg_1061;
    tmp_hwEta_V_load_1_3_1_fu_411_p3 <= 
        p_read6_read5_fu_323_p3 when (tmp_36_2_1_reg_1165(0) = '1') else 
        p_read7_tmp_hwEta_V_l_1_fu_391_p3;
    tmp_hwEta_V_load_1_3_2_fu_635_p3 <= 
        tmp_hwEta_V_load_1_2_fu_430_p3 when (tmp_36_3_2_fu_557_p2(0) = '1') else 
        in_3_hwEta_V_read_1_reg_1053;
    tmp_hwEta_V_load_1_3_fu_373_p3 <= 
        in_1_hwEta_V_read_1_reg_1068 when (tmp_151_reg_1134(0) = '1') else 
        p_read7_tmp_hwEta_V_l_fu_355_p3;
    tmp_hwEta_V_load_1_4_1_fu_606_p3 <= 
        tmp_hwEta_V_load_1_3_1_fu_411_p3 when (tmp_36_3_1_fu_495_p2(0) = '1') else 
        p_read8_tmp_hwEta_V_l_2_fu_576_p3;
    tmp_hwEta_V_load_1_4_fu_542_p3 <= 
        tmp_hwEta_V_load_1_3_fu_373_p3 when (tmp_36_3_fu_439_p2(0) = '1') else 
        p_read8_tmp_hwEta_V_l_1_fu_513_p3;
    tmp_hwEta_V_load_s_fu_482_p3 <= 
        in_1_hwEta_V_read_1_reg_1068 when (tmp_153_reg_1147(0) = '1') else 
        p_read8_tmp_hwEta_V_l_fu_457_p3;
    tmp_hwId_V_load_1_2_s_fu_418_p3 <= 
        p_read15_read_fu_328_p3 when (tmp_36_2_2_reg_1182(0) = '1') else 
        in_2_hwId_V_read_1_reg_987;
    tmp_hwId_V_load_1_3_1_fu_397_p3 <= 
        p_read16_read_fu_313_p3 when (tmp_36_2_1_reg_1165(0) = '1') else 
        p_read17_tmp_hwId_V_l_1_fu_379_p3;
    tmp_hwId_V_load_1_3_fu_361_p3 <= 
        in_1_hwId_V_read_1_reg_994 when (tmp_151_reg_1134(0) = '1') else 
        p_read17_tmp_hwId_V_l_fu_343_p3;
    tmp_hwId_V_load_1_3_s_fu_621_p3 <= 
        tmp_hwId_V_load_1_2_s_fu_418_p3 when (tmp_36_3_2_fu_557_p2(0) = '1') else 
        in_3_hwId_V_read_1_reg_979;
    tmp_hwId_V_load_1_4_1_fu_590_p3 <= 
        tmp_hwId_V_load_1_3_1_fu_397_p3 when (tmp_36_3_1_fu_495_p2(0) = '1') else 
        p_read18_tmp_hwId_V_l_2_fu_562_p3;
    tmp_hwId_V_load_1_4_fu_526_p3 <= 
        tmp_hwId_V_load_1_3_fu_361_p3 when (tmp_36_3_fu_439_p2(0) = '1') else 
        p_read18_tmp_hwId_V_l_1_fu_499_p3;
    tmp_hwId_V_load_s_fu_470_p3 <= 
        in_1_hwId_V_read_1_reg_994 when (tmp_153_reg_1147(0) = '1') else 
        p_read18_tmp_hwId_V_l_fu_443_p3;
    tmp_hwPhi_V_load_1_2_fu_424_p3 <= 
        p_read10_read_fu_333_p3 when (tmp_36_2_2_reg_1182(0) = '1') else 
        in_2_hwPhi_V_read_1_reg_1024;
    tmp_hwPhi_V_load_1_3_1_fu_404_p3 <= 
        p_read11_read_fu_318_p3 when (tmp_36_2_1_reg_1165(0) = '1') else 
        p_read12_tmp_hwPhi_V_1_fu_385_p3;
    tmp_hwPhi_V_load_1_3_2_fu_628_p3 <= 
        tmp_hwPhi_V_load_1_2_fu_424_p3 when (tmp_36_3_2_fu_557_p2(0) = '1') else 
        in_3_hwPhi_V_read_1_reg_1016;
    tmp_hwPhi_V_load_1_3_fu_367_p3 <= 
        in_1_hwPhi_V_read_1_reg_1031 when (tmp_151_reg_1134(0) = '1') else 
        p_read12_tmp_hwPhi_V_s_fu_349_p3;
    tmp_hwPhi_V_load_1_4_1_fu_598_p3 <= 
        tmp_hwPhi_V_load_1_3_1_fu_404_p3 when (tmp_36_3_1_fu_495_p2(0) = '1') else 
        p_read13_tmp_hwPhi_V_2_fu_569_p3;
    tmp_hwPhi_V_load_1_4_fu_534_p3 <= 
        tmp_hwPhi_V_load_1_3_fu_367_p3 when (tmp_36_3_fu_439_p2(0) = '1') else 
        p_read13_tmp_hwPhi_V_1_fu_506_p3;
    tmp_hwPhi_V_load_s_fu_476_p3 <= 
        in_1_hwPhi_V_read_1_reg_1031 when (tmp_153_reg_1147(0) = '1') else 
        p_read13_tmp_hwPhi_V_s_fu_450_p3;
    tmp_hwPt_V_load_1_4_fu_488_p3 <= 
        ap_const_lv16_0 when (tmp_153_reg_1147(0) = '1') else 
        p_read3_tmp_hwPt_V_lo_fu_464_p3;
    tmp_hwPt_V_load_2_1_1_fu_268_p1 <= std_logic_vector(resize(unsigned(tmp_hwPt_V_load_2_1_s_reg_1128),16));
    tmp_hwPt_V_load_2_1_s_fu_233_p3 <= 
        p_read_reg_965 when (tmp_36_1_2_fu_207_p2(0) = '1') else 
        tmp_150_fu_229_p1;
    tmp_hwPt_V_load_2_2_1_17_fu_436_p1 <= std_logic_vector(resize(unsigned(tmp_hwPt_V_load_2_2_s_reg_1199),16));
    tmp_hwPt_V_load_2_2_1_fu_221_p3 <= 
        ap_const_lv16_0 when (tmp_149_fu_199_p3(0) = '1') else 
        p_read1_tmp_hwPt_V_lo_fu_213_p3;
    tmp_hwPt_V_load_2_2_s_fu_307_p3 <= 
        tmp_hwPt_V_load_2_1_s_reg_1128 when (tmp_36_2_2_fu_288_p2(0) = '1') else 
        tmp_152_reg_1142;
    tmp_hwPt_V_load_2_3_1_18_fu_648_p1 <= std_logic_vector(resize(unsigned(tmp_hwPt_V_load_2_3_s_reg_1294),16));
    tmp_hwPt_V_load_2_3_1_fu_300_p3 <= 
        tmp_hwPt_V_load_2_2_1_reg_1121 when (tmp_36_2_1_fu_271_p2(0) = '1') else 
        p_read2_tmp_hwPt_V_lo_1_fu_293_p3;
    tmp_hwPt_V_load_2_3_fu_281_p3 <= 
        ap_const_lv16_0 when (tmp_151_reg_1134(0) = '1') else 
        p_read2_tmp_hwPt_V_lo_fu_275_p3;
    tmp_hwPt_V_load_2_3_s_fu_642_p3 <= 
        tmp_hwPt_V_load_2_2_s_reg_1199 when (tmp_36_3_2_fu_557_p2(0) = '1') else 
        tmp_154_reg_1155;
    tmp_hwPt_V_load_2_4_1_fu_614_p3 <= 
        tmp_hwPt_V_load_2_3_1_reg_1192 when (tmp_36_3_1_fu_495_p2(0) = '1') else 
        p_read3_tmp_hwPt_V_lo_2_fu_583_p3;
    tmp_hwPt_V_load_2_4_fu_550_p3 <= 
        tmp_hwPt_V_load_2_3_reg_1175 when (tmp_36_3_fu_439_p2(0) = '1') else 
        p_read3_tmp_hwPt_V_lo_1_fu_520_p3;
end behav;
