-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tk2calo_tkalgo is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    track_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_0_hwEta_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_1_hwEta_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_2_hwEta_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_3_hwEta_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_4_hwEta_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_5_hwEta_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_6_hwEta_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_0_hwPhi_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_1_hwPhi_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_2_hwPhi_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_3_hwPhi_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_4_hwPhi_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_5_hwPhi_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_6_hwPhi_V_rea : IN STD_LOGIC_VECTOR (8 downto 0);
    track_0_hwZ0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    track_1_hwZ0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    track_2_hwZ0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    track_3_hwZ0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    track_4_hwZ0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    track_5_hwZ0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    track_6_hwZ0_V_read : IN STD_LOGIC_VECTOR (9 downto 0);
    isEle_0_read : IN STD_LOGIC;
    isEle_1_read : IN STD_LOGIC;
    isEle_2_read : IN STD_LOGIC;
    isEle_3_read : IN STD_LOGIC;
    isEle_4_read : IN STD_LOGIC;
    isEle_5_read : IN STD_LOGIC;
    isEle_6_read : IN STD_LOGIC;
    isMu_0_read : IN STD_LOGIC;
    isMu_1_read : IN STD_LOGIC;
    isMu_2_read : IN STD_LOGIC;
    isMu_3_read : IN STD_LOGIC;
    isMu_4_read : IN STD_LOGIC;
    isMu_5_read : IN STD_LOGIC;
    isMu_6_read : IN STD_LOGIC;
    calo_track_link_bit_s : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_31 : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_32 : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_33 : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_34 : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_35 : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_36 : IN STD_LOGIC_VECTOR (4 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (8 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (2 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (9 downto 0);
    ap_return_34 : OUT STD_LOGIC_VECTOR (9 downto 0) );
end;


architecture behav of tk2calo_tkalgo is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_4F : STD_LOGIC_VECTOR (15 downto 0) := "0000000001001111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal track_6_hwPt_V_read_2_reg_1906 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_5_hwPt_V_read_2_reg_1912 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_4_hwPt_V_read_2_reg_1918 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_3_hwPt_V_read_2_reg_1924 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_2_hwPt_V_read_2_reg_1930 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_1_hwPt_V_read_2_reg_1936 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_0_hwPt_V_read_4_reg_1942 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_cond_8_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_8_reg_1948 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_9_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_9_reg_1954 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_10_fu_470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_10_reg_1960 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_11_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_11_reg_1966 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_12_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_12_reg_1972 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond5_13_fu_524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond5_13_reg_1978 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_14_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_14_reg_1984 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_port_reg_track_0_hwEta_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_1_hwEta_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_2_hwEta_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_3_hwEta_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_4_hwEta_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_5_hwEta_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_6_hwEta_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_0_hwPhi_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_1_hwPhi_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_2_hwPhi_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_3_hwPhi_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_4_hwPhi_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_5_hwPhi_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_6_hwPhi_V_rea : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_port_reg_track_0_hwZ0_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_track_1_hwZ0_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_track_2_hwZ0_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_track_3_hwZ0_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_track_4_hwZ0_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_track_5_hwZ0_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_track_6_hwZ0_V_read : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_port_reg_isEle_0_read : STD_LOGIC;
    signal ap_port_reg_isEle_1_read : STD_LOGIC;
    signal ap_port_reg_isEle_2_read : STD_LOGIC;
    signal ap_port_reg_isEle_3_read : STD_LOGIC;
    signal ap_port_reg_isEle_4_read : STD_LOGIC;
    signal ap_port_reg_isEle_5_read : STD_LOGIC;
    signal ap_port_reg_isEle_6_read : STD_LOGIC;
    signal ap_port_reg_isMu_0_read : STD_LOGIC;
    signal ap_port_reg_isMu_1_read : STD_LOGIC;
    signal ap_port_reg_isMu_2_read : STD_LOGIC;
    signal ap_port_reg_isMu_3_read : STD_LOGIC;
    signal ap_port_reg_isMu_4_read : STD_LOGIC;
    signal ap_port_reg_isMu_5_read : STD_LOGIC;
    signal ap_port_reg_isMu_6_read : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_s_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal good_fu_428_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal good_1_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal good_2_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_476_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal good_3_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal good_4_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal good_5_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal good_6_fu_536_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_demorgan_fu_548_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_demorgan_fu_548_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_demorgan_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_560_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_572_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_578_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_572_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_565_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp3_fu_591_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp30_demorgan_fu_607_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp30_demorgan_fu_607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_618_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_624_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_fu_652_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_cast_cast_fu_630_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel_fu_644_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond1_fu_652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel1_fu_658_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp7_fu_680_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp10_fu_696_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp78_demorgan_fu_712_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp78_demorgan_fu_712_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp78_demorgan_fu_712_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_737_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_743_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_737_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_743_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_fu_729_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp86_demorgan_fu_757_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp86_demorgan_fu_757_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_768_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp16_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_768_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_774_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_774_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_fu_802_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_fu_788_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel496_cast_cast_fu_780_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel3_fu_794_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond4_fu_802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond5_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel4_fu_808_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp19_fu_830_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp20_fu_846_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp21_fu_860_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp148_demorgan_fu_876_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp148_demorgan_fu_876_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp148_demorgan_fu_876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp22_fu_882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp23_fu_888_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp25_fu_901_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp26_fu_907_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp25_fu_901_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp26_fu_907_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp24_fu_893_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp156_demorgan_fu_921_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp156_demorgan_fu_921_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp28_fu_932_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp27_fu_926_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp28_fu_932_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp29_fu_938_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp29_fu_938_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_fu_966_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_fu_952_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel504_cast_cast_fu_944_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel6_fu_958_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond7_fu_966_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond8_fu_980_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel7_fu_972_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp30_fu_994_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp31_fu_1010_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp32_fu_1024_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp218_demorgan_fu_1040_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp218_demorgan_fu_1040_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp218_demorgan_fu_1040_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp33_fu_1046_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp34_fu_1052_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp36_fu_1065_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp37_fu_1071_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp36_fu_1065_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp37_fu_1071_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp35_fu_1057_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp38_fu_1085_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp240_demorgan_fu_1101_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp240_demorgan_fu_1101_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp40_fu_1112_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp39_fu_1106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp40_fu_1112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp41_fu_1118_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp41_fu_1118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond10_fu_1146_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond9_fu_1132_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel512_cast_cast_fu_1124_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel9_fu_1138_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond10_fu_1146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond11_fu_1160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel2_fu_1152_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp42_fu_1174_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp43_fu_1188_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp288_demorgan_fu_1204_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp288_demorgan_fu_1204_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp288_demorgan_fu_1204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp44_fu_1210_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp45_fu_1216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_1229_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp48_fu_1235_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp47_fu_1229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp48_fu_1235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp46_fu_1221_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp49_fu_1249_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp310_demorgan_fu_1265_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp310_demorgan_fu_1265_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp51_fu_1276_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp50_fu_1270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp51_fu_1276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp52_fu_1282_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp52_fu_1282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond13_fu_1310_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond12_fu_1296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel520_cast_cast_fu_1288_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel5_fu_1302_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond13_fu_1310_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond14_fu_1324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel8_fu_1316_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp53_fu_1338_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp54_fu_1352_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp358_demorgan_fu_1368_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp358_demorgan_fu_1368_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp358_demorgan_fu_1368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp55_fu_1374_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp56_fu_1380_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp58_fu_1393_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp59_fu_1399_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp58_fu_1393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp59_fu_1399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp57_fu_1385_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp60_fu_1413_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp380_demorgan_fu_1429_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp380_demorgan_fu_1429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp62_fu_1440_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp61_fu_1434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp62_fu_1440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp63_fu_1446_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp63_fu_1446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond16_fu_1474_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond15_fu_1460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel528_cast_cast_fu_1452_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel10_fu_1466_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond16_fu_1474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond17_fu_1488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel11_fu_1480_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp64_fu_1502_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp65_fu_1516_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal sel_tmp428_demorgan_fu_1532_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp428_demorgan_fu_1532_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp428_demorgan_fu_1532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp66_fu_1538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp67_fu_1544_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp69_fu_1557_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp70_fu_1563_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp69_fu_1557_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp70_fu_1563_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp68_fu_1549_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp71_fu_1577_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp450_demorgan_fu_1593_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp450_demorgan_fu_1593_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp73_fu_1604_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp72_fu_1598_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp73_fu_1604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp74_fu_1610_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp74_fu_1610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond19_fu_1638_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond18_fu_1624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel536_cast_cast_fu_1616_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel12_fu_1630_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond19_fu_1638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond20_fu_1652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel13_fu_1644_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal sel_tmp75_fu_1666_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sel_tmp76_fu_1680_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pfout_0_hwPt_V_writ_fu_584_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_1_hwPt_V_writ_fu_853_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_2_hwPt_V_writ_fu_1017_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_3_hwPt_V_writ_fu_1181_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_4_hwPt_V_writ_fu_1345_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_5_hwPt_V_writ_fu_1509_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_6_hwPt_V_writ_fu_1673_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal pfout_0_hwEta_V_wri_fu_688_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_1_hwEta_V_wri_fu_838_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_2_hwEta_V_wri_fu_1002_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_3_hwEta_V_wri_fu_1093_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_4_hwEta_V_wri_fu_1257_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_5_hwEta_V_wri_fu_1405_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_6_hwEta_V_wri_fu_1569_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_0_hwPhi_V_wri_fu_599_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_1_hwPhi_V_wri_fu_749_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_2_hwPhi_V_wri_fu_913_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_3_hwPhi_V_wri_fu_1077_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_4_hwPhi_V_wri_fu_1241_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_5_hwPhi_V_wri_fu_1421_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_6_hwPhi_V_wri_fu_1585_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal pfout_0_hwId_V_writ_fu_672_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_1_hwId_V_writ_fu_822_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_2_hwId_V_writ_fu_986_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_3_hwId_V_writ_fu_1166_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_4_hwId_V_writ_fu_1330_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_5_hwId_V_writ_fu_1494_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_6_hwId_V_writ_fu_1658_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal pfout_0_hwZ0_V_writ_fu_704_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pfout_1_hwZ0_V_writ_fu_868_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pfout_2_hwZ0_V_writ_fu_1032_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pfout_3_hwZ0_V_writ_fu_1196_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pfout_4_hwZ0_V_writ_fu_1360_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pfout_5_hwZ0_V_writ_fu_1524_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pfout_6_hwZ0_V_writ_fu_1688_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_state1 = ap_const_lv1_1) and not((ap_start = ap_const_logic_0)))) then
                ap_port_reg_isEle_0_read <= isEle_0_read;
                ap_port_reg_isEle_1_read <= isEle_1_read;
                ap_port_reg_isEle_2_read <= isEle_2_read;
                ap_port_reg_isEle_3_read <= isEle_3_read;
                ap_port_reg_isEle_4_read <= isEle_4_read;
                ap_port_reg_isEle_5_read <= isEle_5_read;
                ap_port_reg_isEle_6_read <= isEle_6_read;
                ap_port_reg_isMu_0_read <= isMu_0_read;
                ap_port_reg_isMu_1_read <= isMu_1_read;
                ap_port_reg_isMu_2_read <= isMu_2_read;
                ap_port_reg_isMu_3_read <= isMu_3_read;
                ap_port_reg_isMu_4_read <= isMu_4_read;
                ap_port_reg_isMu_5_read <= isMu_5_read;
                ap_port_reg_isMu_6_read <= isMu_6_read;
                ap_port_reg_track_0_hwEta_V_rea <= track_0_hwEta_V_rea;
                ap_port_reg_track_0_hwPhi_V_rea <= track_0_hwPhi_V_rea;
                ap_port_reg_track_0_hwZ0_V_read <= track_0_hwZ0_V_read;
                ap_port_reg_track_1_hwEta_V_rea <= track_1_hwEta_V_rea;
                ap_port_reg_track_1_hwPhi_V_rea <= track_1_hwPhi_V_rea;
                ap_port_reg_track_1_hwZ0_V_read <= track_1_hwZ0_V_read;
                ap_port_reg_track_2_hwEta_V_rea <= track_2_hwEta_V_rea;
                ap_port_reg_track_2_hwPhi_V_rea <= track_2_hwPhi_V_rea;
                ap_port_reg_track_2_hwZ0_V_read <= track_2_hwZ0_V_read;
                ap_port_reg_track_3_hwEta_V_rea <= track_3_hwEta_V_rea;
                ap_port_reg_track_3_hwPhi_V_rea <= track_3_hwPhi_V_rea;
                ap_port_reg_track_3_hwZ0_V_read <= track_3_hwZ0_V_read;
                ap_port_reg_track_4_hwEta_V_rea <= track_4_hwEta_V_rea;
                ap_port_reg_track_4_hwPhi_V_rea <= track_4_hwPhi_V_rea;
                ap_port_reg_track_4_hwZ0_V_read <= track_4_hwZ0_V_read;
                ap_port_reg_track_5_hwEta_V_rea <= track_5_hwEta_V_rea;
                ap_port_reg_track_5_hwPhi_V_rea <= track_5_hwPhi_V_rea;
                ap_port_reg_track_5_hwZ0_V_read <= track_5_hwZ0_V_read;
                ap_port_reg_track_6_hwEta_V_rea <= track_6_hwEta_V_rea;
                ap_port_reg_track_6_hwPhi_V_rea <= track_6_hwPhi_V_rea;
                ap_port_reg_track_6_hwZ0_V_read <= track_6_hwZ0_V_read;
                or_cond1_9_reg_1954 <= or_cond1_9_fu_452_p2;
                or_cond2_10_reg_1960 <= or_cond2_10_fu_470_p2;
                or_cond3_11_reg_1966 <= or_cond3_11_fu_488_p2;
                or_cond4_12_reg_1972 <= or_cond4_12_fu_506_p2;
                or_cond5_13_reg_1978 <= or_cond5_13_fu_524_p2;
                or_cond6_14_reg_1984 <= or_cond6_14_fu_542_p2;
                or_cond_8_reg_1948 <= or_cond_8_fu_434_p2;
                track_0_hwPt_V_read_4_reg_1942 <= track_0_hwPt_V_read;
                track_1_hwPt_V_read_2_reg_1936 <= track_1_hwPt_V_read;
                track_2_hwPt_V_read_2_reg_1930 <= track_2_hwPt_V_read;
                track_3_hwPt_V_read_2_reg_1924 <= track_3_hwPt_V_read;
                track_4_hwPt_V_read_2_reg_1918 <= track_4_hwPt_V_read;
                track_5_hwPt_V_read_2_reg_1912 <= track_5_hwPt_V_read;
                track_6_hwPt_V_read_2_reg_1906 <= track_6_hwPt_V_read;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (not((ap_start = ap_const_logic_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1 downto 1);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1)) or ((ap_const_lv1_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_state1 = ap_const_lv1_1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2)
    begin
        if (((ap_const_lv1_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= pfout_0_hwPt_V_writ_fu_584_p3;
    ap_return_1 <= pfout_1_hwPt_V_writ_fu_853_p3;
    ap_return_10 <= pfout_3_hwEta_V_wri_fu_1093_p3;
    ap_return_11 <= pfout_4_hwEta_V_wri_fu_1257_p3;
    ap_return_12 <= pfout_5_hwEta_V_wri_fu_1405_p3;
    ap_return_13 <= pfout_6_hwEta_V_wri_fu_1569_p3;
    ap_return_14 <= pfout_0_hwPhi_V_wri_fu_599_p3;
    ap_return_15 <= pfout_1_hwPhi_V_wri_fu_749_p3;
    ap_return_16 <= pfout_2_hwPhi_V_wri_fu_913_p3;
    ap_return_17 <= pfout_3_hwPhi_V_wri_fu_1077_p3;
    ap_return_18 <= pfout_4_hwPhi_V_wri_fu_1241_p3;
    ap_return_19 <= pfout_5_hwPhi_V_wri_fu_1421_p3;
    ap_return_2 <= pfout_2_hwPt_V_writ_fu_1017_p3;
    ap_return_20 <= pfout_6_hwPhi_V_wri_fu_1585_p3;
    ap_return_21 <= pfout_0_hwId_V_writ_fu_672_p3;
    ap_return_22 <= pfout_1_hwId_V_writ_fu_822_p3;
    ap_return_23 <= pfout_2_hwId_V_writ_fu_986_p3;
    ap_return_24 <= pfout_3_hwId_V_writ_fu_1166_p3;
    ap_return_25 <= pfout_4_hwId_V_writ_fu_1330_p3;
    ap_return_26 <= pfout_5_hwId_V_writ_fu_1494_p3;
    ap_return_27 <= pfout_6_hwId_V_writ_fu_1658_p3;
    ap_return_28 <= pfout_0_hwZ0_V_writ_fu_704_p3;
    ap_return_29 <= pfout_1_hwZ0_V_writ_fu_868_p3;
    ap_return_3 <= pfout_3_hwPt_V_writ_fu_1181_p3;
    ap_return_30 <= pfout_2_hwZ0_V_writ_fu_1032_p3;
    ap_return_31 <= pfout_3_hwZ0_V_writ_fu_1196_p3;
    ap_return_32 <= pfout_4_hwZ0_V_writ_fu_1360_p3;
    ap_return_33 <= pfout_5_hwZ0_V_writ_fu_1524_p3;
    ap_return_34 <= pfout_6_hwZ0_V_writ_fu_1688_p3;
    ap_return_4 <= pfout_4_hwPt_V_writ_fu_1345_p3;
    ap_return_5 <= pfout_5_hwPt_V_writ_fu_1509_p3;
    ap_return_6 <= pfout_6_hwPt_V_writ_fu_1673_p3;
    ap_return_7 <= pfout_0_hwEta_V_wri_fu_688_p3;
    ap_return_8 <= pfout_1_hwEta_V_wri_fu_838_p3;
    ap_return_9 <= pfout_2_hwEta_V_wri_fu_1002_p3;
    good_1_fu_446_p2 <= "1" when (calo_track_link_bit_31 = ap_const_lv5_0) else "0";
    good_2_fu_464_p2 <= "1" when (calo_track_link_bit_32 = ap_const_lv5_0) else "0";
    good_3_fu_482_p2 <= "1" when (calo_track_link_bit_33 = ap_const_lv5_0) else "0";
    good_4_fu_500_p2 <= "1" when (calo_track_link_bit_34 = ap_const_lv5_0) else "0";
    good_5_fu_518_p2 <= "1" when (calo_track_link_bit_35 = ap_const_lv5_0) else "0";
    good_6_fu_536_p2 <= "1" when (calo_track_link_bit_36 = ap_const_lv5_0) else "0";
    good_fu_428_p2 <= "1" when (calo_track_link_bit_s = ap_const_lv5_0) else "0";
    newSel10_fu_1466_p3 <= 
        ap_const_lv3_3 when (sel_tmp63_fu_1446_p2(0) = '1') else 
        ap_const_lv3_4;
    newSel11_fu_1480_p3 <= 
        newSel528_cast_cast_fu_1452_p3 when (or_cond15_fu_1460_p2(0) = '1') else 
        newSel10_fu_1466_p3;
    newSel12_fu_1630_p3 <= 
        ap_const_lv3_3 when (sel_tmp74_fu_1610_p2(0) = '1') else 
        ap_const_lv3_4;
    newSel13_fu_1644_p3 <= 
        newSel536_cast_cast_fu_1616_p3 when (or_cond18_fu_1624_p2(0) = '1') else 
        newSel12_fu_1630_p3;
    newSel1_fu_658_p3 <= 
        newSel_cast_cast_fu_630_p3 when (or_cond_fu_638_p2(0) = '1') else 
        newSel_fu_644_p3;
    newSel2_fu_1152_p3 <= 
        newSel512_cast_cast_fu_1124_p3 when (or_cond9_fu_1132_p2(0) = '1') else 
        newSel9_fu_1138_p3;
    newSel3_fu_794_p3 <= 
        ap_const_lv3_3 when (sel_tmp18_fu_774_p2(0) = '1') else 
        ap_const_lv3_4;
    newSel496_cast_cast_fu_780_p3 <= 
        ap_const_lv3_3 when (sel_tmp15_fu_743_p2(0) = '1') else 
        ap_const_lv3_0;
    newSel4_fu_808_p3 <= 
        newSel496_cast_cast_fu_780_p3 when (or_cond3_fu_788_p2(0) = '1') else 
        newSel3_fu_794_p3;
    newSel504_cast_cast_fu_944_p3 <= 
        ap_const_lv3_3 when (sel_tmp26_fu_907_p2(0) = '1') else 
        ap_const_lv3_0;
    newSel512_cast_cast_fu_1124_p3 <= 
        ap_const_lv3_3 when (sel_tmp37_fu_1071_p2(0) = '1') else 
        ap_const_lv3_0;
    newSel520_cast_cast_fu_1288_p3 <= 
        ap_const_lv3_3 when (sel_tmp48_fu_1235_p2(0) = '1') else 
        ap_const_lv3_0;
    newSel528_cast_cast_fu_1452_p3 <= 
        ap_const_lv3_3 when (sel_tmp59_fu_1399_p2(0) = '1') else 
        ap_const_lv3_0;
    newSel536_cast_cast_fu_1616_p3 <= 
        ap_const_lv3_3 when (sel_tmp70_fu_1563_p2(0) = '1') else 
        ap_const_lv3_0;
    newSel5_fu_1302_p3 <= 
        ap_const_lv3_3 when (sel_tmp52_fu_1282_p2(0) = '1') else 
        ap_const_lv3_4;
    newSel6_fu_958_p3 <= 
        ap_const_lv3_3 when (sel_tmp29_fu_938_p2(0) = '1') else 
        ap_const_lv3_4;
    newSel7_fu_972_p3 <= 
        newSel504_cast_cast_fu_944_p3 when (or_cond6_fu_952_p2(0) = '1') else 
        newSel6_fu_958_p3;
    newSel8_fu_1316_p3 <= 
        newSel520_cast_cast_fu_1288_p3 when (or_cond12_fu_1296_p2(0) = '1') else 
        newSel5_fu_1302_p3;
    newSel9_fu_1138_p3 <= 
        ap_const_lv3_3 when (sel_tmp41_fu_1118_p2(0) = '1') else 
        ap_const_lv3_4;
    newSel_cast_cast_fu_630_p3 <= 
        ap_const_lv3_3 when (sel_tmp2_fu_578_p2(0) = '1') else 
        ap_const_lv3_0;
    newSel_fu_644_p3 <= 
        ap_const_lv3_3 when (sel_tmp6_fu_624_p2(0) = '1') else 
        ap_const_lv3_4;
    or_cond10_fu_1146_p1 <= (0=>ap_port_reg_isMu_3_read, others=>'-');
    or_cond10_fu_1146_p2 <= (sel_tmp41_fu_1118_p2 or or_cond10_fu_1146_p1);
    or_cond11_fu_1160_p2 <= (or_cond9_fu_1132_p2 or or_cond10_fu_1146_p2);
    or_cond12_fu_1296_p2 <= (sel_tmp48_fu_1235_p2 or sel_tmp45_fu_1216_p2);
    or_cond13_fu_1310_p1 <= (0=>ap_port_reg_isMu_4_read, others=>'-');
    or_cond13_fu_1310_p2 <= (sel_tmp52_fu_1282_p2 or or_cond13_fu_1310_p1);
    or_cond14_fu_1324_p2 <= (or_cond12_fu_1296_p2 or or_cond13_fu_1310_p2);
    or_cond15_fu_1460_p2 <= (sel_tmp59_fu_1399_p2 or sel_tmp56_fu_1380_p2);
    or_cond16_fu_1474_p1 <= (0=>ap_port_reg_isMu_5_read, others=>'-');
    or_cond16_fu_1474_p2 <= (sel_tmp63_fu_1446_p2 or or_cond16_fu_1474_p1);
    or_cond17_fu_1488_p2 <= (or_cond15_fu_1460_p2 or or_cond16_fu_1474_p2);
    or_cond18_fu_1624_p2 <= (sel_tmp70_fu_1563_p2 or sel_tmp67_fu_1544_p2);
    or_cond19_fu_1638_p1 <= (0=>ap_port_reg_isMu_6_read, others=>'-');
    or_cond19_fu_1638_p2 <= (sel_tmp74_fu_1610_p2 or or_cond19_fu_1638_p1);
    or_cond1_9_fu_452_p2 <= (tmp_1_fu_440_p2 and good_1_fu_446_p2);
    or_cond1_fu_652_p1 <= (0=>ap_port_reg_isMu_0_read, others=>'-');
    or_cond1_fu_652_p2 <= (sel_tmp6_fu_624_p2 or or_cond1_fu_652_p1);
    or_cond20_fu_1652_p2 <= (or_cond18_fu_1624_p2 or or_cond19_fu_1638_p2);
    or_cond2_10_fu_470_p2 <= (tmp_2_fu_458_p2 and good_2_fu_464_p2);
    or_cond2_fu_666_p2 <= (or_cond_fu_638_p2 or or_cond1_fu_652_p2);
    or_cond3_11_fu_488_p2 <= (tmp_3_fu_476_p2 and good_3_fu_482_p2);
    or_cond3_fu_788_p2 <= (sel_tmp15_fu_743_p2 or sel_tmp12_fu_724_p2);
    or_cond4_12_fu_506_p2 <= (tmp_4_fu_494_p2 and good_4_fu_500_p2);
    or_cond4_fu_802_p1 <= (0=>ap_port_reg_isMu_1_read, others=>'-');
    or_cond4_fu_802_p2 <= (sel_tmp18_fu_774_p2 or or_cond4_fu_802_p1);
    or_cond5_13_fu_524_p2 <= (tmp_5_fu_512_p2 and good_5_fu_518_p2);
    or_cond5_fu_816_p2 <= (or_cond3_fu_788_p2 or or_cond4_fu_802_p2);
    or_cond6_14_fu_542_p2 <= (tmp_6_fu_530_p2 and good_6_fu_536_p2);
    or_cond6_fu_952_p2 <= (sel_tmp26_fu_907_p2 or sel_tmp23_fu_888_p2);
    or_cond7_fu_966_p1 <= (0=>ap_port_reg_isMu_2_read, others=>'-');
    or_cond7_fu_966_p2 <= (sel_tmp29_fu_938_p2 or or_cond7_fu_966_p1);
    or_cond8_fu_980_p2 <= (or_cond6_fu_952_p2 or or_cond7_fu_966_p2);
    or_cond9_fu_1132_p2 <= (sel_tmp37_fu_1071_p2 or sel_tmp34_fu_1052_p2);
    or_cond_8_fu_434_p2 <= (tmp_s_fu_422_p2 and good_fu_428_p2);
    or_cond_fu_638_p2 <= (sel_tmp2_fu_578_p2 or sel_tmp9_fu_560_p2);
    pfout_0_hwEta_V_wri_fu_688_p3 <= 
        ap_port_reg_track_0_hwEta_V_rea when (sel_tmp2_fu_578_p2(0) = '1') else 
        sel_tmp7_fu_680_p3;
    pfout_0_hwId_V_writ_fu_672_p3 <= 
        newSel1_fu_658_p3 when (or_cond2_fu_666_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_0_hwPhi_V_wri_fu_599_p3 <= 
        ap_port_reg_track_0_hwPhi_V_rea when (sel_tmp2_fu_578_p2(0) = '1') else 
        sel_tmp3_fu_591_p3;
    pfout_0_hwPt_V_writ_fu_584_p3 <= 
        track_0_hwPt_V_read_4_reg_1942 when (sel_tmp2_fu_578_p2(0) = '1') else 
        sel_tmp_fu_565_p3;
    pfout_0_hwZ0_V_writ_fu_704_p3 <= 
        ap_port_reg_track_0_hwZ0_V_read when (sel_tmp2_fu_578_p2(0) = '1') else 
        sel_tmp10_fu_696_p3;
    pfout_1_hwEta_V_wri_fu_838_p3 <= 
        ap_port_reg_track_1_hwEta_V_rea when (sel_tmp15_fu_743_p2(0) = '1') else 
        sel_tmp19_fu_830_p3;
    pfout_1_hwId_V_writ_fu_822_p3 <= 
        newSel4_fu_808_p3 when (or_cond5_fu_816_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_1_hwPhi_V_wri_fu_749_p3 <= 
        ap_port_reg_track_1_hwPhi_V_rea when (sel_tmp15_fu_743_p2(0) = '1') else 
        sel_tmp13_fu_729_p3;
    pfout_1_hwPt_V_writ_fu_853_p3 <= 
        track_1_hwPt_V_read_2_reg_1936 when (sel_tmp15_fu_743_p2(0) = '1') else 
        sel_tmp20_fu_846_p3;
    pfout_1_hwZ0_V_writ_fu_868_p3 <= 
        ap_port_reg_track_1_hwZ0_V_read when (sel_tmp15_fu_743_p2(0) = '1') else 
        sel_tmp21_fu_860_p3;
    pfout_2_hwEta_V_wri_fu_1002_p3 <= 
        ap_port_reg_track_2_hwEta_V_rea when (sel_tmp26_fu_907_p2(0) = '1') else 
        sel_tmp30_fu_994_p3;
    pfout_2_hwId_V_writ_fu_986_p3 <= 
        newSel7_fu_972_p3 when (or_cond8_fu_980_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_2_hwPhi_V_wri_fu_913_p3 <= 
        ap_port_reg_track_2_hwPhi_V_rea when (sel_tmp26_fu_907_p2(0) = '1') else 
        sel_tmp24_fu_893_p3;
    pfout_2_hwPt_V_writ_fu_1017_p3 <= 
        track_2_hwPt_V_read_2_reg_1930 when (sel_tmp26_fu_907_p2(0) = '1') else 
        sel_tmp31_fu_1010_p3;
    pfout_2_hwZ0_V_writ_fu_1032_p3 <= 
        ap_port_reg_track_2_hwZ0_V_read when (sel_tmp26_fu_907_p2(0) = '1') else 
        sel_tmp32_fu_1024_p3;
    pfout_3_hwEta_V_wri_fu_1093_p3 <= 
        ap_port_reg_track_3_hwEta_V_rea when (sel_tmp37_fu_1071_p2(0) = '1') else 
        sel_tmp38_fu_1085_p3;
    pfout_3_hwId_V_writ_fu_1166_p3 <= 
        newSel2_fu_1152_p3 when (or_cond11_fu_1160_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_3_hwPhi_V_wri_fu_1077_p3 <= 
        ap_port_reg_track_3_hwPhi_V_rea when (sel_tmp37_fu_1071_p2(0) = '1') else 
        sel_tmp35_fu_1057_p3;
    pfout_3_hwPt_V_writ_fu_1181_p3 <= 
        track_3_hwPt_V_read_2_reg_1924 when (sel_tmp37_fu_1071_p2(0) = '1') else 
        sel_tmp42_fu_1174_p3;
    pfout_3_hwZ0_V_writ_fu_1196_p3 <= 
        ap_port_reg_track_3_hwZ0_V_read when (sel_tmp37_fu_1071_p2(0) = '1') else 
        sel_tmp43_fu_1188_p3;
    pfout_4_hwEta_V_wri_fu_1257_p3 <= 
        ap_port_reg_track_4_hwEta_V_rea when (sel_tmp48_fu_1235_p2(0) = '1') else 
        sel_tmp49_fu_1249_p3;
    pfout_4_hwId_V_writ_fu_1330_p3 <= 
        newSel8_fu_1316_p3 when (or_cond14_fu_1324_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_4_hwPhi_V_wri_fu_1241_p3 <= 
        ap_port_reg_track_4_hwPhi_V_rea when (sel_tmp48_fu_1235_p2(0) = '1') else 
        sel_tmp46_fu_1221_p3;
    pfout_4_hwPt_V_writ_fu_1345_p3 <= 
        track_4_hwPt_V_read_2_reg_1918 when (sel_tmp48_fu_1235_p2(0) = '1') else 
        sel_tmp53_fu_1338_p3;
    pfout_4_hwZ0_V_writ_fu_1360_p3 <= 
        ap_port_reg_track_4_hwZ0_V_read when (sel_tmp48_fu_1235_p2(0) = '1') else 
        sel_tmp54_fu_1352_p3;
    pfout_5_hwEta_V_wri_fu_1405_p3 <= 
        ap_port_reg_track_5_hwEta_V_rea when (sel_tmp59_fu_1399_p2(0) = '1') else 
        sel_tmp57_fu_1385_p3;
    pfout_5_hwId_V_writ_fu_1494_p3 <= 
        newSel11_fu_1480_p3 when (or_cond17_fu_1488_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_5_hwPhi_V_wri_fu_1421_p3 <= 
        ap_port_reg_track_5_hwPhi_V_rea when (sel_tmp59_fu_1399_p2(0) = '1') else 
        sel_tmp60_fu_1413_p3;
    pfout_5_hwPt_V_writ_fu_1509_p3 <= 
        track_5_hwPt_V_read_2_reg_1912 when (sel_tmp59_fu_1399_p2(0) = '1') else 
        sel_tmp64_fu_1502_p3;
    pfout_5_hwZ0_V_writ_fu_1524_p3 <= 
        ap_port_reg_track_5_hwZ0_V_read when (sel_tmp59_fu_1399_p2(0) = '1') else 
        sel_tmp65_fu_1516_p3;
    pfout_6_hwEta_V_wri_fu_1569_p3 <= 
        ap_port_reg_track_6_hwEta_V_rea when (sel_tmp70_fu_1563_p2(0) = '1') else 
        sel_tmp68_fu_1549_p3;
    pfout_6_hwId_V_writ_fu_1658_p3 <= 
        newSel13_fu_1644_p3 when (or_cond20_fu_1652_p2(0) = '1') else 
        ap_const_lv3_0;
    pfout_6_hwPhi_V_wri_fu_1585_p3 <= 
        ap_port_reg_track_6_hwPhi_V_rea when (sel_tmp70_fu_1563_p2(0) = '1') else 
        sel_tmp71_fu_1577_p3;
    pfout_6_hwPt_V_writ_fu_1673_p3 <= 
        track_6_hwPt_V_read_2_reg_1906 when (sel_tmp70_fu_1563_p2(0) = '1') else 
        sel_tmp75_fu_1666_p3;
    pfout_6_hwZ0_V_writ_fu_1688_p3 <= 
        ap_port_reg_track_6_hwZ0_V_read when (sel_tmp70_fu_1563_p2(0) = '1') else 
        sel_tmp76_fu_1680_p3;
    sel_tmp10_fu_696_p3 <= 
        ap_const_lv10_0 when (sel_tmp9_fu_560_p2(0) = '1') else 
        ap_port_reg_track_0_hwZ0_V_read;
    sel_tmp11_fu_718_p2 <= (sel_tmp78_demorgan_fu_712_p2 xor ap_const_lv1_1);
    sel_tmp12_fu_724_p2 <= (or_cond1_9_reg_1954 and sel_tmp11_fu_718_p2);
    sel_tmp13_fu_729_p3 <= 
        ap_const_lv9_0 when (sel_tmp12_fu_724_p2(0) = '1') else 
        ap_port_reg_track_1_hwPhi_V_rea;
    sel_tmp148_demorgan_fu_876_p0 <= (0=>ap_port_reg_isMu_2_read, others=>'-');
    sel_tmp148_demorgan_fu_876_p1 <= (0=>ap_port_reg_isEle_2_read, others=>'-');
    sel_tmp148_demorgan_fu_876_p2 <= (sel_tmp148_demorgan_fu_876_p0 or sel_tmp148_demorgan_fu_876_p1);
    sel_tmp14_fu_737_p0 <= (0=>ap_port_reg_isMu_1_read, others=>'-');
    sel_tmp14_fu_737_p2 <= (sel_tmp14_fu_737_p0 xor ap_const_lv1_1);
    sel_tmp156_demorgan_fu_921_p1 <= (0=>ap_port_reg_isEle_2_read, others=>'-');
    sel_tmp156_demorgan_fu_921_p2 <= (or_cond2_10_reg_1960 or sel_tmp156_demorgan_fu_921_p1);
    sel_tmp15_fu_743_p0 <= (0=>ap_port_reg_isEle_1_read, others=>'-');
    sel_tmp15_fu_743_p2 <= (sel_tmp15_fu_743_p0 and sel_tmp14_fu_737_p2);
    sel_tmp16_fu_762_p2 <= (sel_tmp86_demorgan_fu_757_p2 xor ap_const_lv1_1);
    sel_tmp17_fu_768_p0 <= (0=>ap_port_reg_isMu_1_read, others=>'-');
    sel_tmp17_fu_768_p2 <= (sel_tmp17_fu_768_p0 or sel_tmp16_fu_762_p2);
    sel_tmp18_fu_774_p1 <= (0=>ap_port_reg_isEle_1_read, others=>'-');
    sel_tmp18_fu_774_p2 <= (sel_tmp17_fu_768_p2 and sel_tmp18_fu_774_p1);
    sel_tmp19_fu_830_p3 <= 
        ap_const_lv9_0 when (sel_tmp12_fu_724_p2(0) = '1') else 
        ap_port_reg_track_1_hwEta_V_rea;
    sel_tmp1_fu_572_p0 <= (0=>ap_port_reg_isMu_0_read, others=>'-');
    sel_tmp1_fu_572_p2 <= (sel_tmp1_fu_572_p0 xor ap_const_lv1_1);
    sel_tmp20_fu_846_p3 <= 
        ap_const_lv16_0 when (sel_tmp12_fu_724_p2(0) = '1') else 
        track_1_hwPt_V_read_2_reg_1936;
    sel_tmp218_demorgan_fu_1040_p0 <= (0=>ap_port_reg_isMu_3_read, others=>'-');
    sel_tmp218_demorgan_fu_1040_p1 <= (0=>ap_port_reg_isEle_3_read, others=>'-');
    sel_tmp218_demorgan_fu_1040_p2 <= (sel_tmp218_demorgan_fu_1040_p0 or sel_tmp218_demorgan_fu_1040_p1);
    sel_tmp21_fu_860_p3 <= 
        ap_const_lv10_0 when (sel_tmp12_fu_724_p2(0) = '1') else 
        ap_port_reg_track_1_hwZ0_V_read;
    sel_tmp22_fu_882_p2 <= (sel_tmp148_demorgan_fu_876_p2 xor ap_const_lv1_1);
    sel_tmp23_fu_888_p2 <= (or_cond2_10_reg_1960 and sel_tmp22_fu_882_p2);
    sel_tmp240_demorgan_fu_1101_p1 <= (0=>ap_port_reg_isEle_3_read, others=>'-');
    sel_tmp240_demorgan_fu_1101_p2 <= (or_cond3_11_reg_1966 or sel_tmp240_demorgan_fu_1101_p1);
    sel_tmp24_fu_893_p3 <= 
        ap_const_lv9_0 when (sel_tmp23_fu_888_p2(0) = '1') else 
        ap_port_reg_track_2_hwPhi_V_rea;
    sel_tmp25_fu_901_p0 <= (0=>ap_port_reg_isMu_2_read, others=>'-');
    sel_tmp25_fu_901_p2 <= (sel_tmp25_fu_901_p0 xor ap_const_lv1_1);
    sel_tmp26_fu_907_p0 <= (0=>ap_port_reg_isEle_2_read, others=>'-');
    sel_tmp26_fu_907_p2 <= (sel_tmp26_fu_907_p0 and sel_tmp25_fu_901_p2);
    sel_tmp27_fu_926_p2 <= (sel_tmp156_demorgan_fu_921_p2 xor ap_const_lv1_1);
    sel_tmp288_demorgan_fu_1204_p0 <= (0=>ap_port_reg_isMu_4_read, others=>'-');
    sel_tmp288_demorgan_fu_1204_p1 <= (0=>ap_port_reg_isEle_4_read, others=>'-');
    sel_tmp288_demorgan_fu_1204_p2 <= (sel_tmp288_demorgan_fu_1204_p0 or sel_tmp288_demorgan_fu_1204_p1);
    sel_tmp28_fu_932_p0 <= (0=>ap_port_reg_isMu_2_read, others=>'-');
    sel_tmp28_fu_932_p2 <= (sel_tmp28_fu_932_p0 or sel_tmp27_fu_926_p2);
    sel_tmp29_fu_938_p1 <= (0=>ap_port_reg_isEle_2_read, others=>'-');
    sel_tmp29_fu_938_p2 <= (sel_tmp28_fu_932_p2 and sel_tmp29_fu_938_p1);
    sel_tmp2_fu_578_p0 <= (0=>ap_port_reg_isEle_0_read, others=>'-');
    sel_tmp2_fu_578_p2 <= (sel_tmp2_fu_578_p0 and sel_tmp1_fu_572_p2);
    sel_tmp30_demorgan_fu_607_p1 <= (0=>ap_port_reg_isEle_0_read, others=>'-');
    sel_tmp30_demorgan_fu_607_p2 <= (or_cond_8_reg_1948 or sel_tmp30_demorgan_fu_607_p1);
    sel_tmp30_fu_994_p3 <= 
        ap_const_lv9_0 when (sel_tmp23_fu_888_p2(0) = '1') else 
        ap_port_reg_track_2_hwEta_V_rea;
    sel_tmp310_demorgan_fu_1265_p1 <= (0=>ap_port_reg_isEle_4_read, others=>'-');
    sel_tmp310_demorgan_fu_1265_p2 <= (or_cond4_12_reg_1972 or sel_tmp310_demorgan_fu_1265_p1);
    sel_tmp31_fu_1010_p3 <= 
        ap_const_lv16_0 when (sel_tmp23_fu_888_p2(0) = '1') else 
        track_2_hwPt_V_read_2_reg_1930;
    sel_tmp32_fu_1024_p3 <= 
        ap_const_lv10_0 when (sel_tmp23_fu_888_p2(0) = '1') else 
        ap_port_reg_track_2_hwZ0_V_read;
    sel_tmp33_fu_1046_p2 <= (sel_tmp218_demorgan_fu_1040_p2 xor ap_const_lv1_1);
    sel_tmp34_fu_1052_p2 <= (or_cond3_11_reg_1966 and sel_tmp33_fu_1046_p2);
    sel_tmp358_demorgan_fu_1368_p0 <= (0=>ap_port_reg_isMu_5_read, others=>'-');
    sel_tmp358_demorgan_fu_1368_p1 <= (0=>ap_port_reg_isEle_5_read, others=>'-');
    sel_tmp358_demorgan_fu_1368_p2 <= (sel_tmp358_demorgan_fu_1368_p0 or sel_tmp358_demorgan_fu_1368_p1);
    sel_tmp35_fu_1057_p3 <= 
        ap_const_lv9_0 when (sel_tmp34_fu_1052_p2(0) = '1') else 
        ap_port_reg_track_3_hwPhi_V_rea;
    sel_tmp36_fu_1065_p0 <= (0=>ap_port_reg_isMu_3_read, others=>'-');
    sel_tmp36_fu_1065_p2 <= (sel_tmp36_fu_1065_p0 xor ap_const_lv1_1);
    sel_tmp37_fu_1071_p0 <= (0=>ap_port_reg_isEle_3_read, others=>'-');
    sel_tmp37_fu_1071_p2 <= (sel_tmp37_fu_1071_p0 and sel_tmp36_fu_1065_p2);
    sel_tmp380_demorgan_fu_1429_p1 <= (0=>ap_port_reg_isEle_5_read, others=>'-');
    sel_tmp380_demorgan_fu_1429_p2 <= (or_cond5_13_reg_1978 or sel_tmp380_demorgan_fu_1429_p1);
    sel_tmp38_fu_1085_p3 <= 
        ap_const_lv9_0 when (sel_tmp34_fu_1052_p2(0) = '1') else 
        ap_port_reg_track_3_hwEta_V_rea;
    sel_tmp39_fu_1106_p2 <= (sel_tmp240_demorgan_fu_1101_p2 xor ap_const_lv1_1);
    sel_tmp3_fu_591_p3 <= 
        ap_const_lv9_0 when (sel_tmp9_fu_560_p2(0) = '1') else 
        ap_port_reg_track_0_hwPhi_V_rea;
    sel_tmp40_fu_1112_p0 <= (0=>ap_port_reg_isMu_3_read, others=>'-');
    sel_tmp40_fu_1112_p2 <= (sel_tmp40_fu_1112_p0 or sel_tmp39_fu_1106_p2);
    sel_tmp41_fu_1118_p1 <= (0=>ap_port_reg_isEle_3_read, others=>'-');
    sel_tmp41_fu_1118_p2 <= (sel_tmp40_fu_1112_p2 and sel_tmp41_fu_1118_p1);
    sel_tmp428_demorgan_fu_1532_p0 <= (0=>ap_port_reg_isMu_6_read, others=>'-');
    sel_tmp428_demorgan_fu_1532_p1 <= (0=>ap_port_reg_isEle_6_read, others=>'-');
    sel_tmp428_demorgan_fu_1532_p2 <= (sel_tmp428_demorgan_fu_1532_p0 or sel_tmp428_demorgan_fu_1532_p1);
    sel_tmp42_fu_1174_p3 <= 
        ap_const_lv16_0 when (sel_tmp34_fu_1052_p2(0) = '1') else 
        track_3_hwPt_V_read_2_reg_1924;
    sel_tmp43_fu_1188_p3 <= 
        ap_const_lv10_0 when (sel_tmp34_fu_1052_p2(0) = '1') else 
        ap_port_reg_track_3_hwZ0_V_read;
    sel_tmp44_fu_1210_p2 <= (sel_tmp288_demorgan_fu_1204_p2 xor ap_const_lv1_1);
    sel_tmp450_demorgan_fu_1593_p1 <= (0=>ap_port_reg_isEle_6_read, others=>'-');
    sel_tmp450_demorgan_fu_1593_p2 <= (or_cond6_14_reg_1984 or sel_tmp450_demorgan_fu_1593_p1);
    sel_tmp45_fu_1216_p2 <= (or_cond4_12_reg_1972 and sel_tmp44_fu_1210_p2);
    sel_tmp46_fu_1221_p3 <= 
        ap_const_lv9_0 when (sel_tmp45_fu_1216_p2(0) = '1') else 
        ap_port_reg_track_4_hwPhi_V_rea;
    sel_tmp47_fu_1229_p0 <= (0=>ap_port_reg_isMu_4_read, others=>'-');
    sel_tmp47_fu_1229_p2 <= (sel_tmp47_fu_1229_p0 xor ap_const_lv1_1);
    sel_tmp48_fu_1235_p0 <= (0=>ap_port_reg_isEle_4_read, others=>'-');
    sel_tmp48_fu_1235_p2 <= (sel_tmp48_fu_1235_p0 and sel_tmp47_fu_1229_p2);
    sel_tmp49_fu_1249_p3 <= 
        ap_const_lv9_0 when (sel_tmp45_fu_1216_p2(0) = '1') else 
        ap_port_reg_track_4_hwEta_V_rea;
    sel_tmp4_fu_612_p2 <= (sel_tmp30_demorgan_fu_607_p2 xor ap_const_lv1_1);
    sel_tmp50_fu_1270_p2 <= (sel_tmp310_demorgan_fu_1265_p2 xor ap_const_lv1_1);
    sel_tmp51_fu_1276_p0 <= (0=>ap_port_reg_isMu_4_read, others=>'-');
    sel_tmp51_fu_1276_p2 <= (sel_tmp51_fu_1276_p0 or sel_tmp50_fu_1270_p2);
    sel_tmp52_fu_1282_p1 <= (0=>ap_port_reg_isEle_4_read, others=>'-');
    sel_tmp52_fu_1282_p2 <= (sel_tmp51_fu_1276_p2 and sel_tmp52_fu_1282_p1);
    sel_tmp53_fu_1338_p3 <= 
        ap_const_lv16_0 when (sel_tmp45_fu_1216_p2(0) = '1') else 
        track_4_hwPt_V_read_2_reg_1918;
    sel_tmp54_fu_1352_p3 <= 
        ap_const_lv10_0 when (sel_tmp45_fu_1216_p2(0) = '1') else 
        ap_port_reg_track_4_hwZ0_V_read;
    sel_tmp55_fu_1374_p2 <= (sel_tmp358_demorgan_fu_1368_p2 xor ap_const_lv1_1);
    sel_tmp56_fu_1380_p2 <= (or_cond5_13_reg_1978 and sel_tmp55_fu_1374_p2);
    sel_tmp57_fu_1385_p3 <= 
        ap_const_lv9_0 when (sel_tmp56_fu_1380_p2(0) = '1') else 
        ap_port_reg_track_5_hwEta_V_rea;
    sel_tmp58_fu_1393_p0 <= (0=>ap_port_reg_isMu_5_read, others=>'-');
    sel_tmp58_fu_1393_p2 <= (sel_tmp58_fu_1393_p0 xor ap_const_lv1_1);
    sel_tmp59_fu_1399_p0 <= (0=>ap_port_reg_isEle_5_read, others=>'-');
    sel_tmp59_fu_1399_p2 <= (sel_tmp59_fu_1399_p0 and sel_tmp58_fu_1393_p2);
    sel_tmp5_fu_618_p0 <= (0=>ap_port_reg_isMu_0_read, others=>'-');
    sel_tmp5_fu_618_p2 <= (sel_tmp5_fu_618_p0 or sel_tmp4_fu_612_p2);
    sel_tmp60_fu_1413_p3 <= 
        ap_const_lv9_0 when (sel_tmp56_fu_1380_p2(0) = '1') else 
        ap_port_reg_track_5_hwPhi_V_rea;
    sel_tmp61_fu_1434_p2 <= (sel_tmp380_demorgan_fu_1429_p2 xor ap_const_lv1_1);
    sel_tmp62_fu_1440_p0 <= (0=>ap_port_reg_isMu_5_read, others=>'-');
    sel_tmp62_fu_1440_p2 <= (sel_tmp62_fu_1440_p0 or sel_tmp61_fu_1434_p2);
    sel_tmp63_fu_1446_p1 <= (0=>ap_port_reg_isEle_5_read, others=>'-');
    sel_tmp63_fu_1446_p2 <= (sel_tmp62_fu_1440_p2 and sel_tmp63_fu_1446_p1);
    sel_tmp64_fu_1502_p3 <= 
        ap_const_lv16_0 when (sel_tmp56_fu_1380_p2(0) = '1') else 
        track_5_hwPt_V_read_2_reg_1912;
    sel_tmp65_fu_1516_p3 <= 
        ap_const_lv10_0 when (sel_tmp56_fu_1380_p2(0) = '1') else 
        ap_port_reg_track_5_hwZ0_V_read;
    sel_tmp66_fu_1538_p2 <= (sel_tmp428_demorgan_fu_1532_p2 xor ap_const_lv1_1);
    sel_tmp67_fu_1544_p2 <= (or_cond6_14_reg_1984 and sel_tmp66_fu_1538_p2);
    sel_tmp68_fu_1549_p3 <= 
        ap_const_lv9_0 when (sel_tmp67_fu_1544_p2(0) = '1') else 
        ap_port_reg_track_6_hwEta_V_rea;
    sel_tmp69_fu_1557_p0 <= (0=>ap_port_reg_isMu_6_read, others=>'-');
    sel_tmp69_fu_1557_p2 <= (sel_tmp69_fu_1557_p0 xor ap_const_lv1_1);
    sel_tmp6_fu_624_p1 <= (0=>ap_port_reg_isEle_0_read, others=>'-');
    sel_tmp6_fu_624_p2 <= (sel_tmp5_fu_618_p2 and sel_tmp6_fu_624_p1);
    sel_tmp70_fu_1563_p0 <= (0=>ap_port_reg_isEle_6_read, others=>'-');
    sel_tmp70_fu_1563_p2 <= (sel_tmp70_fu_1563_p0 and sel_tmp69_fu_1557_p2);
    sel_tmp71_fu_1577_p3 <= 
        ap_const_lv9_0 when (sel_tmp67_fu_1544_p2(0) = '1') else 
        ap_port_reg_track_6_hwPhi_V_rea;
    sel_tmp72_fu_1598_p2 <= (sel_tmp450_demorgan_fu_1593_p2 xor ap_const_lv1_1);
    sel_tmp73_fu_1604_p0 <= (0=>ap_port_reg_isMu_6_read, others=>'-');
    sel_tmp73_fu_1604_p2 <= (sel_tmp73_fu_1604_p0 or sel_tmp72_fu_1598_p2);
    sel_tmp74_fu_1610_p1 <= (0=>ap_port_reg_isEle_6_read, others=>'-');
    sel_tmp74_fu_1610_p2 <= (sel_tmp73_fu_1604_p2 and sel_tmp74_fu_1610_p1);
    sel_tmp75_fu_1666_p3 <= 
        ap_const_lv16_0 when (sel_tmp67_fu_1544_p2(0) = '1') else 
        track_6_hwPt_V_read_2_reg_1906;
    sel_tmp76_fu_1680_p3 <= 
        ap_const_lv10_0 when (sel_tmp67_fu_1544_p2(0) = '1') else 
        ap_port_reg_track_6_hwZ0_V_read;
    sel_tmp78_demorgan_fu_712_p0 <= (0=>ap_port_reg_isMu_1_read, others=>'-');
    sel_tmp78_demorgan_fu_712_p1 <= (0=>ap_port_reg_isEle_1_read, others=>'-');
    sel_tmp78_demorgan_fu_712_p2 <= (sel_tmp78_demorgan_fu_712_p0 or sel_tmp78_demorgan_fu_712_p1);
    sel_tmp7_fu_680_p3 <= 
        ap_const_lv9_0 when (sel_tmp9_fu_560_p2(0) = '1') else 
        ap_port_reg_track_0_hwEta_V_rea;
    sel_tmp86_demorgan_fu_757_p1 <= (0=>ap_port_reg_isEle_1_read, others=>'-');
    sel_tmp86_demorgan_fu_757_p2 <= (or_cond1_9_reg_1954 or sel_tmp86_demorgan_fu_757_p1);
    sel_tmp8_demorgan_fu_548_p0 <= (0=>ap_port_reg_isMu_0_read, others=>'-');
    sel_tmp8_demorgan_fu_548_p1 <= (0=>ap_port_reg_isEle_0_read, others=>'-');
    sel_tmp8_demorgan_fu_548_p2 <= (sel_tmp8_demorgan_fu_548_p0 or sel_tmp8_demorgan_fu_548_p1);
    sel_tmp8_fu_554_p2 <= (sel_tmp8_demorgan_fu_548_p2 xor ap_const_lv1_1);
    sel_tmp9_fu_560_p2 <= (or_cond_8_reg_1948 and sel_tmp8_fu_554_p2);
    sel_tmp_fu_565_p3 <= 
        ap_const_lv16_0 when (sel_tmp9_fu_560_p2(0) = '1') else 
        track_0_hwPt_V_read_4_reg_1942;
    tmp_1_fu_440_p2 <= "1" when (signed(track_1_hwPt_V_read) > signed(ap_const_lv16_4F)) else "0";
    tmp_2_fu_458_p2 <= "1" when (signed(track_2_hwPt_V_read) > signed(ap_const_lv16_4F)) else "0";
    tmp_3_fu_476_p2 <= "1" when (signed(track_3_hwPt_V_read) > signed(ap_const_lv16_4F)) else "0";
    tmp_4_fu_494_p2 <= "1" when (signed(track_4_hwPt_V_read) > signed(ap_const_lv16_4F)) else "0";
    tmp_5_fu_512_p2 <= "1" when (signed(track_5_hwPt_V_read) > signed(ap_const_lv16_4F)) else "0";
    tmp_6_fu_530_p2 <= "1" when (signed(track_6_hwPt_V_read) > signed(ap_const_lv16_4F)) else "0";
    tmp_s_fu_422_p2 <= "1" when (signed(track_0_hwPt_V_read) > signed(ap_const_lv16_4F)) else "0";
end behav;
