-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tk2em_sumtk is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    track_0_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_1_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_2_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_3_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_4_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_5_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    track_6_hwPt_V_read : IN STD_LOGIC_VECTOR (15 downto 0);
    calo_track_link_bit_s : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_7 : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_8 : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_9 : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_10 : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_11 : IN STD_LOGIC_VECTOR (4 downto 0);
    calo_track_link_bit_12 : IN STD_LOGIC_VECTOR (4 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of tk2em_sumtk is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal p_read_s_fu_134_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_s_reg_762 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_0_hwPt_V_read_1_fu_150_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_0_hwPt_V_read_1_reg_768 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_1_fu_166_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_1_reg_774 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_0_hwPt_V_read_2_fu_182_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_0_hwPt_V_read_2_reg_780 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_2_fu_198_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_read_2_reg_786 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_6_hwPt_V_read_1_reg_792 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_pipeline_reg_pp0_iter1_track_6_hwPt_V_read_1_reg_792 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_pipeline_reg_pp0_iter2_track_6_hwPt_V_read_1_reg_792 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_5_hwPt_V_read_1_reg_801 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_pipeline_reg_pp0_iter1_track_5_hwPt_V_read_1_reg_801 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_4_hwPt_V_read_1_reg_810 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_pipeline_reg_pp0_iter1_track_4_hwPt_V_read_1_reg_810 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_3_hwPt_V_read_1_reg_819 : STD_LOGIC_VECTOR (15 downto 0);
    signal track_2_hwPt_V_read_1_reg_828 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_0_1_fu_215_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_0_1_reg_837 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_2_fu_222_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_843 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_226_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_848 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_230_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_853 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_4_reg_853 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_234_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_858 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_5_reg_858 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_238_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_863 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_6_reg_863 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_tmp_6_reg_863 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_V_1_1_07_1_1_fu_255_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_1_1_07_1_1_reg_868 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_reg_874 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_879 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_reg_884 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_11_reg_884 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_889 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_12_reg_889 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_894 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_13_reg_894 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_tmp_13_reg_894 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_07_1_2_1_fu_315_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_2_1_reg_899 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_16_reg_905 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_910 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_18_reg_915 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_920 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_19_reg_920 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_reg_925 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_20_reg_925 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_tmp_20_reg_925 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_V_3_1_07_1_3_fu_375_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_3_1_07_1_3_reg_930 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_23_reg_936 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_reg_941 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_reg_946 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_25_reg_946 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_reg_951 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_26_reg_951 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_reg_956 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_27_reg_956 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_tmp_27_reg_956 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_07_1_4_1_fu_435_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_4_1_reg_961 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_30_reg_967 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_reg_972 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_reg_977 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_32_reg_977 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_reg_982 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_33_reg_982 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_reg_987 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_tmp_34_reg_987 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_tmp_34_reg_987 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_V_0_2_07_1_0_1_fu_486_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_0_2_07_1_0_1_reg_992 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_1_2_fu_496_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_1_2_reg_998 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_2_2_07_1_2_1_fu_506_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_2_2_07_1_2_1_reg_1004 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_3_2_fu_516_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_3_2_reg_1010 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_4_2_07_1_4_1_fu_526_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_4_2_07_1_4_1_reg_1016 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_0_3_fu_536_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_0_3_reg_1022 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_1_3_07_1_1_2_fu_546_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_1_3_07_1_1_2_reg_1028 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_2_3_fu_556_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_2_3_reg_1034 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_3_3_07_1_3_2_fu_566_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_3_3_07_1_3_2_reg_1040 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_4_3_fu_576_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_4_3_reg_1046 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_0_4_07_1_0_3_fu_586_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_0_4_07_1_0_3_reg_1052 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_1_4_fu_596_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_1_4_reg_1058 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_2_4_07_1_2_3_fu_606_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_2_4_07_1_2_3_reg_1064 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_3_4_fu_616_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_3_4_reg_1070 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_4_4_07_1_4_3_fu_626_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_4_4_07_1_4_3_reg_1076 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_0_5_fu_636_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_0_5_reg_1082 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_1_5_07_1_1_4_fu_646_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_1_5_07_1_1_4_reg_1088 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_2_5_fu_656_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_2_5_reg_1094 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_3_5_07_1_3_4_fu_666_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_3_5_07_1_3_4_reg_1100 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_4_5_fu_676_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_07_1_4_5_reg_1106 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter0_preg : STD_LOGIC := '0';
    signal ap_port_reg_track_1_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_track_2_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_track_3_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_track_4_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_track_5_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_track_6_hwPt_V_read : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_port_reg_calo_track_link_bit_7 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_port_reg_calo_track_link_bit_8 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_port_reg_calo_track_link_bit_9 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_port_reg_calo_track_link_bit_10 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_port_reg_calo_track_link_bit_11 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_port_reg_calo_track_link_bit_12 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_fu_130_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_142_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_158_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_174_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_190_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_206_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_V_0_1_fu_210_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_8_fu_242_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_V_1_1_fu_250_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_15_fu_302_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_V_2_1_fu_310_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_22_fu_362_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_V_3_1_fu_370_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_29_fu_422_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sum_V_4_1_fu_430_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_0_2_fu_482_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_1_2_fu_492_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_2_2_fu_502_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_3_2_fu_512_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_4_2_fu_522_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_0_3_fu_532_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_1_3_fu_542_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_2_3_fu_552_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_3_3_fu_562_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_4_3_fu_572_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_0_4_fu_582_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_1_4_fu_592_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_2_4_fu_602_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_3_4_fu_612_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_4_4_fu_622_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_0_5_fu_632_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_1_5_fu_642_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_2_5_fu_652_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_3_5_fu_662_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_4_5_fu_672_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_0_6_fu_682_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_1_6_fu_692_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_2_6_fu_702_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_3_6_fu_712_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sum_V_4_6_fu_722_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_0_V_write_ass_fu_686_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_1_V_write_ass_fu_696_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_2_V_write_ass_fu_706_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_3_V_write_ass_fu_716_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sumtk_4_V_write_ass_fu_726_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_pipeline_idle_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_preg <= ap_const_logic_0;
            else
                if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then 
                    ap_enable_reg_pp0_iter0_preg <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_const_logic_1 = ap_enable_reg_pp0_iter2)))) then 
                    ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
                elsif ((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_lv1_1 = ap_CS_fsm_pp0_stage1))) then
                ap_pipeline_reg_pp0_iter1_tmp_11_reg_884 <= tmp_11_reg_884;
                ap_pipeline_reg_pp0_iter1_tmp_12_reg_889 <= tmp_12_reg_889;
                ap_pipeline_reg_pp0_iter1_tmp_13_reg_894 <= tmp_13_reg_894;
                ap_pipeline_reg_pp0_iter1_tmp_18_reg_915 <= tmp_18_reg_915;
                ap_pipeline_reg_pp0_iter1_tmp_19_reg_920 <= tmp_19_reg_920;
                ap_pipeline_reg_pp0_iter1_tmp_20_reg_925 <= tmp_20_reg_925;
                ap_pipeline_reg_pp0_iter1_tmp_25_reg_946 <= tmp_25_reg_946;
                ap_pipeline_reg_pp0_iter1_tmp_26_reg_951 <= tmp_26_reg_951;
                ap_pipeline_reg_pp0_iter1_tmp_27_reg_956 <= tmp_27_reg_956;
                ap_pipeline_reg_pp0_iter1_tmp_32_reg_977 <= tmp_32_reg_977;
                ap_pipeline_reg_pp0_iter1_tmp_33_reg_982 <= tmp_33_reg_982;
                ap_pipeline_reg_pp0_iter1_tmp_34_reg_987 <= tmp_34_reg_987;
                ap_pipeline_reg_pp0_iter1_tmp_4_reg_853 <= tmp_4_reg_853;
                ap_pipeline_reg_pp0_iter1_tmp_5_reg_858 <= tmp_5_reg_858;
                ap_pipeline_reg_pp0_iter1_tmp_6_reg_863 <= tmp_6_reg_863;
                ap_pipeline_reg_pp0_iter1_track_4_hwPt_V_read_1_reg_810 <= track_4_hwPt_V_read_1_reg_810;
                ap_pipeline_reg_pp0_iter1_track_5_hwPt_V_read_1_reg_801 <= track_5_hwPt_V_read_1_reg_801;
                ap_pipeline_reg_pp0_iter1_track_6_hwPt_V_read_1_reg_792 <= track_6_hwPt_V_read_1_reg_792;
                ap_pipeline_reg_pp0_iter2_tmp_13_reg_894 <= ap_pipeline_reg_pp0_iter1_tmp_13_reg_894;
                ap_pipeline_reg_pp0_iter2_tmp_20_reg_925 <= ap_pipeline_reg_pp0_iter1_tmp_20_reg_925;
                ap_pipeline_reg_pp0_iter2_tmp_27_reg_956 <= ap_pipeline_reg_pp0_iter1_tmp_27_reg_956;
                ap_pipeline_reg_pp0_iter2_tmp_34_reg_987 <= ap_pipeline_reg_pp0_iter1_tmp_34_reg_987;
                ap_pipeline_reg_pp0_iter2_tmp_6_reg_863 <= ap_pipeline_reg_pp0_iter1_tmp_6_reg_863;
                ap_pipeline_reg_pp0_iter2_track_6_hwPt_V_read_1_reg_792 <= ap_pipeline_reg_pp0_iter1_track_6_hwPt_V_read_1_reg_792;
                p_07_1_0_1_reg_837 <= p_07_1_0_1_fu_215_p3;
                p_07_1_0_3_reg_1022 <= p_07_1_0_3_fu_536_p3;
                p_07_1_0_5_reg_1082 <= p_07_1_0_5_fu_636_p3;
                p_07_1_2_1_reg_899 <= p_07_1_2_1_fu_315_p3;
                p_07_1_2_3_reg_1034 <= p_07_1_2_3_fu_556_p3;
                p_07_1_2_5_reg_1094 <= p_07_1_2_5_fu_656_p3;
                p_07_1_4_1_reg_961 <= p_07_1_4_1_fu_435_p3;
                p_07_1_4_3_reg_1046 <= p_07_1_4_3_fu_576_p3;
                p_07_1_4_5_reg_1106 <= p_07_1_4_5_fu_676_p3;
                sum_V_1_1_07_1_1_reg_868 <= sum_V_1_1_07_1_1_fu_255_p3;
                sum_V_1_3_07_1_1_2_reg_1028 <= sum_V_1_3_07_1_1_2_fu_546_p3;
                sum_V_1_5_07_1_1_4_reg_1088 <= sum_V_1_5_07_1_1_4_fu_646_p3;
                sum_V_3_1_07_1_3_reg_930 <= sum_V_3_1_07_1_3_fu_375_p3;
                sum_V_3_3_07_1_3_2_reg_1040 <= sum_V_3_3_07_1_3_2_fu_566_p3;
                sum_V_3_5_07_1_3_4_reg_1100 <= sum_V_3_5_07_1_3_4_fu_666_p3;
                tmp_10_reg_879 <= ap_port_reg_calo_track_link_bit_9(1 downto 1);
                tmp_11_reg_884 <= ap_port_reg_calo_track_link_bit_10(1 downto 1);
                tmp_12_reg_889 <= ap_port_reg_calo_track_link_bit_11(1 downto 1);
                tmp_13_reg_894 <= ap_port_reg_calo_track_link_bit_12(1 downto 1);
                tmp_16_reg_905 <= ap_port_reg_calo_track_link_bit_8(2 downto 2);
                tmp_17_reg_910 <= ap_port_reg_calo_track_link_bit_9(2 downto 2);
                tmp_18_reg_915 <= ap_port_reg_calo_track_link_bit_10(2 downto 2);
                tmp_19_reg_920 <= ap_port_reg_calo_track_link_bit_11(2 downto 2);
                tmp_20_reg_925 <= ap_port_reg_calo_track_link_bit_12(2 downto 2);
                tmp_23_reg_936 <= ap_port_reg_calo_track_link_bit_8(3 downto 3);
                tmp_24_reg_941 <= ap_port_reg_calo_track_link_bit_9(3 downto 3);
                tmp_25_reg_946 <= ap_port_reg_calo_track_link_bit_10(3 downto 3);
                tmp_26_reg_951 <= ap_port_reg_calo_track_link_bit_11(3 downto 3);
                tmp_27_reg_956 <= ap_port_reg_calo_track_link_bit_12(3 downto 3);
                tmp_2_reg_843 <= tmp_2_fu_222_p1;
                tmp_30_reg_967 <= ap_port_reg_calo_track_link_bit_8(4 downto 4);
                tmp_31_reg_972 <= ap_port_reg_calo_track_link_bit_9(4 downto 4);
                tmp_32_reg_977 <= ap_port_reg_calo_track_link_bit_10(4 downto 4);
                tmp_33_reg_982 <= ap_port_reg_calo_track_link_bit_11(4 downto 4);
                tmp_34_reg_987 <= ap_port_reg_calo_track_link_bit_12(4 downto 4);
                tmp_3_reg_848 <= tmp_3_fu_226_p1;
                tmp_4_reg_853 <= tmp_4_fu_230_p1;
                tmp_5_reg_858 <= tmp_5_fu_234_p1;
                tmp_6_reg_863 <= tmp_6_fu_238_p1;
                tmp_9_reg_874 <= ap_port_reg_calo_track_link_bit_8(1 downto 1);
                track_2_hwPt_V_read_1_reg_828 <= ap_port_reg_track_2_hwPt_V_read;
                track_3_hwPt_V_read_1_reg_819 <= ap_port_reg_track_3_hwPt_V_read;
                track_4_hwPt_V_read_1_reg_810 <= ap_port_reg_track_4_hwPt_V_read;
                track_5_hwPt_V_read_1_reg_801 <= ap_port_reg_track_5_hwPt_V_read;
                track_6_hwPt_V_read_1_reg_792 <= ap_port_reg_track_6_hwPt_V_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then
                ap_port_reg_calo_track_link_bit_10 <= calo_track_link_bit_10;
                ap_port_reg_calo_track_link_bit_11 <= calo_track_link_bit_11;
                ap_port_reg_calo_track_link_bit_12 <= calo_track_link_bit_12;
                ap_port_reg_calo_track_link_bit_7 <= calo_track_link_bit_7;
                ap_port_reg_calo_track_link_bit_8 <= calo_track_link_bit_8;
                ap_port_reg_calo_track_link_bit_9 <= calo_track_link_bit_9;
                ap_port_reg_track_1_hwPt_V_read <= track_1_hwPt_V_read;
                ap_port_reg_track_2_hwPt_V_read <= track_2_hwPt_V_read;
                ap_port_reg_track_3_hwPt_V_read <= track_3_hwPt_V_read;
                ap_port_reg_track_4_hwPt_V_read <= track_4_hwPt_V_read;
                ap_port_reg_track_5_hwPt_V_read <= track_5_hwPt_V_read;
                ap_port_reg_track_6_hwPt_V_read <= track_6_hwPt_V_read;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then
                p_07_1_1_2_reg_998 <= p_07_1_1_2_fu_496_p3;
                p_07_1_1_4_reg_1058 <= p_07_1_1_4_fu_596_p3;
                p_07_1_3_2_reg_1010 <= p_07_1_3_2_fu_516_p3;
                p_07_1_3_4_reg_1070 <= p_07_1_3_4_fu_616_p3;
                p_read_1_reg_774 <= p_read_1_fu_166_p3;
                p_read_2_reg_786 <= p_read_2_fu_198_p3;
                p_read_s_reg_762 <= p_read_s_fu_134_p3;
                sum_V_0_2_07_1_0_1_reg_992 <= sum_V_0_2_07_1_0_1_fu_486_p3;
                sum_V_0_4_07_1_0_3_reg_1052 <= sum_V_0_4_07_1_0_3_fu_586_p3;
                sum_V_2_2_07_1_2_1_reg_1004 <= sum_V_2_2_07_1_2_1_fu_506_p3;
                sum_V_2_4_07_1_2_3_reg_1064 <= sum_V_2_4_07_1_2_3_fu_606_p3;
                sum_V_4_2_07_1_4_1_reg_1016 <= sum_V_4_2_07_1_4_1_fu_526_p3;
                sum_V_4_4_07_1_4_3_reg_1076 <= sum_V_4_4_07_1_4_3_fu_626_p3;
                track_0_hwPt_V_read_1_reg_768 <= track_0_hwPt_V_read_1_fu_150_p3;
                track_0_hwPt_V_read_2_reg_780 <= track_0_hwPt_V_read_2_fu_182_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_pipeline_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and not((ap_const_logic_1 = ap_pipeline_idle_pp0)) and not(((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_pipeline_idle_pp0))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "XX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0 downto 0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1 downto 1);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0)) or ((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_preg)
    begin
        if ((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1)) then 
            ap_enable_reg_pp0_iter0 <= ap_start;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_preg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_pipeline_idle_pp0_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2))) then 
            ap_pipeline_idle_pp0 <= ap_const_logic_1;
        else 
            ap_pipeline_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1)
    begin
        if (((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_const_lv1_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= sumtk_0_V_write_ass_fu_686_p3;
    ap_return_1 <= sumtk_1_V_write_ass_fu_696_p3;
    ap_return_2 <= sumtk_2_V_write_ass_fu_706_p3;
    ap_return_3 <= sumtk_3_V_write_ass_fu_716_p3;
    ap_return_4 <= sumtk_4_V_write_ass_fu_726_p3;
    p_07_1_0_1_fu_215_p3 <= 
        sum_V_0_1_fu_210_p2 when (tmp_1_fu_206_p1(0) = '1') else 
        p_read_s_reg_762;
    p_07_1_0_3_fu_536_p3 <= 
        sum_V_0_3_fu_532_p2 when (tmp_3_reg_848(0) = '1') else 
        sum_V_0_2_07_1_0_1_reg_992;
    p_07_1_0_5_fu_636_p3 <= 
        sum_V_0_5_fu_632_p2 when (ap_pipeline_reg_pp0_iter1_tmp_5_reg_858(0) = '1') else 
        sum_V_0_4_07_1_0_3_reg_1052;
    p_07_1_1_2_fu_496_p3 <= 
        sum_V_1_2_fu_492_p2 when (tmp_9_reg_874(0) = '1') else 
        sum_V_1_1_07_1_1_reg_868;
    p_07_1_1_4_fu_596_p3 <= 
        sum_V_1_4_fu_592_p2 when (ap_pipeline_reg_pp0_iter1_tmp_11_reg_884(0) = '1') else 
        sum_V_1_3_07_1_1_2_reg_1028;
    p_07_1_2_1_fu_315_p3 <= 
        sum_V_2_1_fu_310_p2 when (tmp_15_fu_302_p3(0) = '1') else 
        p_read_1_reg_774;
    p_07_1_2_3_fu_556_p3 <= 
        sum_V_2_3_fu_552_p2 when (tmp_17_reg_910(0) = '1') else 
        sum_V_2_2_07_1_2_1_reg_1004;
    p_07_1_2_5_fu_656_p3 <= 
        sum_V_2_5_fu_652_p2 when (ap_pipeline_reg_pp0_iter1_tmp_19_reg_920(0) = '1') else 
        sum_V_2_4_07_1_2_3_reg_1064;
    p_07_1_3_2_fu_516_p3 <= 
        sum_V_3_2_fu_512_p2 when (tmp_23_reg_936(0) = '1') else 
        sum_V_3_1_07_1_3_reg_930;
    p_07_1_3_4_fu_616_p3 <= 
        sum_V_3_4_fu_612_p2 when (ap_pipeline_reg_pp0_iter1_tmp_25_reg_946(0) = '1') else 
        sum_V_3_3_07_1_3_2_reg_1040;
    p_07_1_4_1_fu_435_p3 <= 
        sum_V_4_1_fu_430_p2 when (tmp_29_fu_422_p3(0) = '1') else 
        p_read_2_reg_786;
    p_07_1_4_3_fu_576_p3 <= 
        sum_V_4_3_fu_572_p2 when (tmp_31_reg_972(0) = '1') else 
        sum_V_4_2_07_1_4_1_reg_1016;
    p_07_1_4_5_fu_676_p3 <= 
        sum_V_4_5_fu_672_p2 when (ap_pipeline_reg_pp0_iter1_tmp_33_reg_982(0) = '1') else 
        sum_V_4_4_07_1_4_3_reg_1076;
    p_read_1_fu_166_p3 <= 
        track_0_hwPt_V_read when (tmp_14_fu_158_p3(0) = '1') else 
        ap_const_lv16_0;
    p_read_2_fu_198_p3 <= 
        track_0_hwPt_V_read when (tmp_28_fu_190_p3(0) = '1') else 
        ap_const_lv16_0;
    p_read_s_fu_134_p3 <= 
        track_0_hwPt_V_read when (tmp_fu_130_p1(0) = '1') else 
        ap_const_lv16_0;
    sum_V_0_1_fu_210_p2 <= std_logic_vector(unsigned(ap_port_reg_track_1_hwPt_V_read) + unsigned(p_read_s_reg_762));
    sum_V_0_2_07_1_0_1_fu_486_p3 <= 
        sum_V_0_2_fu_482_p2 when (tmp_2_reg_843(0) = '1') else 
        p_07_1_0_1_reg_837;
    sum_V_0_2_fu_482_p2 <= std_logic_vector(unsigned(track_2_hwPt_V_read_1_reg_828) + unsigned(p_07_1_0_1_reg_837));
    sum_V_0_3_fu_532_p2 <= std_logic_vector(unsigned(track_3_hwPt_V_read_1_reg_819) + unsigned(sum_V_0_2_07_1_0_1_reg_992));
    sum_V_0_4_07_1_0_3_fu_586_p3 <= 
        sum_V_0_4_fu_582_p2 when (ap_pipeline_reg_pp0_iter1_tmp_4_reg_853(0) = '1') else 
        p_07_1_0_3_reg_1022;
    sum_V_0_4_fu_582_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter1_track_4_hwPt_V_read_1_reg_810) + unsigned(p_07_1_0_3_reg_1022));
    sum_V_0_5_fu_632_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter1_track_5_hwPt_V_read_1_reg_801) + unsigned(sum_V_0_4_07_1_0_3_reg_1052));
    sum_V_0_6_fu_682_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter2_track_6_hwPt_V_read_1_reg_792) + unsigned(p_07_1_0_5_reg_1082));
    sum_V_1_1_07_1_1_fu_255_p3 <= 
        sum_V_1_1_fu_250_p2 when (tmp_8_fu_242_p3(0) = '1') else 
        track_0_hwPt_V_read_1_reg_768;
    sum_V_1_1_fu_250_p2 <= std_logic_vector(unsigned(ap_port_reg_track_1_hwPt_V_read) + unsigned(track_0_hwPt_V_read_1_reg_768));
    sum_V_1_2_fu_492_p2 <= std_logic_vector(unsigned(track_2_hwPt_V_read_1_reg_828) + unsigned(sum_V_1_1_07_1_1_reg_868));
    sum_V_1_3_07_1_1_2_fu_546_p3 <= 
        sum_V_1_3_fu_542_p2 when (tmp_10_reg_879(0) = '1') else 
        p_07_1_1_2_reg_998;
    sum_V_1_3_fu_542_p2 <= std_logic_vector(unsigned(track_3_hwPt_V_read_1_reg_819) + unsigned(p_07_1_1_2_reg_998));
    sum_V_1_4_fu_592_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter1_track_4_hwPt_V_read_1_reg_810) + unsigned(sum_V_1_3_07_1_1_2_reg_1028));
    sum_V_1_5_07_1_1_4_fu_646_p3 <= 
        sum_V_1_5_fu_642_p2 when (ap_pipeline_reg_pp0_iter1_tmp_12_reg_889(0) = '1') else 
        p_07_1_1_4_reg_1058;
    sum_V_1_5_fu_642_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter1_track_5_hwPt_V_read_1_reg_801) + unsigned(p_07_1_1_4_reg_1058));
    sum_V_1_6_fu_692_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter2_track_6_hwPt_V_read_1_reg_792) + unsigned(sum_V_1_5_07_1_1_4_reg_1088));
    sum_V_2_1_fu_310_p2 <= std_logic_vector(unsigned(ap_port_reg_track_1_hwPt_V_read) + unsigned(p_read_1_reg_774));
    sum_V_2_2_07_1_2_1_fu_506_p3 <= 
        sum_V_2_2_fu_502_p2 when (tmp_16_reg_905(0) = '1') else 
        p_07_1_2_1_reg_899;
    sum_V_2_2_fu_502_p2 <= std_logic_vector(unsigned(track_2_hwPt_V_read_1_reg_828) + unsigned(p_07_1_2_1_reg_899));
    sum_V_2_3_fu_552_p2 <= std_logic_vector(unsigned(track_3_hwPt_V_read_1_reg_819) + unsigned(sum_V_2_2_07_1_2_1_reg_1004));
    sum_V_2_4_07_1_2_3_fu_606_p3 <= 
        sum_V_2_4_fu_602_p2 when (ap_pipeline_reg_pp0_iter1_tmp_18_reg_915(0) = '1') else 
        p_07_1_2_3_reg_1034;
    sum_V_2_4_fu_602_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter1_track_4_hwPt_V_read_1_reg_810) + unsigned(p_07_1_2_3_reg_1034));
    sum_V_2_5_fu_652_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter1_track_5_hwPt_V_read_1_reg_801) + unsigned(sum_V_2_4_07_1_2_3_reg_1064));
    sum_V_2_6_fu_702_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter2_track_6_hwPt_V_read_1_reg_792) + unsigned(p_07_1_2_5_reg_1094));
    sum_V_3_1_07_1_3_fu_375_p3 <= 
        sum_V_3_1_fu_370_p2 when (tmp_22_fu_362_p3(0) = '1') else 
        track_0_hwPt_V_read_2_reg_780;
    sum_V_3_1_fu_370_p2 <= std_logic_vector(unsigned(ap_port_reg_track_1_hwPt_V_read) + unsigned(track_0_hwPt_V_read_2_reg_780));
    sum_V_3_2_fu_512_p2 <= std_logic_vector(unsigned(track_2_hwPt_V_read_1_reg_828) + unsigned(sum_V_3_1_07_1_3_reg_930));
    sum_V_3_3_07_1_3_2_fu_566_p3 <= 
        sum_V_3_3_fu_562_p2 when (tmp_24_reg_941(0) = '1') else 
        p_07_1_3_2_reg_1010;
    sum_V_3_3_fu_562_p2 <= std_logic_vector(unsigned(track_3_hwPt_V_read_1_reg_819) + unsigned(p_07_1_3_2_reg_1010));
    sum_V_3_4_fu_612_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter1_track_4_hwPt_V_read_1_reg_810) + unsigned(sum_V_3_3_07_1_3_2_reg_1040));
    sum_V_3_5_07_1_3_4_fu_666_p3 <= 
        sum_V_3_5_fu_662_p2 when (ap_pipeline_reg_pp0_iter1_tmp_26_reg_951(0) = '1') else 
        p_07_1_3_4_reg_1070;
    sum_V_3_5_fu_662_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter1_track_5_hwPt_V_read_1_reg_801) + unsigned(p_07_1_3_4_reg_1070));
    sum_V_3_6_fu_712_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter2_track_6_hwPt_V_read_1_reg_792) + unsigned(sum_V_3_5_07_1_3_4_reg_1100));
    sum_V_4_1_fu_430_p2 <= std_logic_vector(unsigned(ap_port_reg_track_1_hwPt_V_read) + unsigned(p_read_2_reg_786));
    sum_V_4_2_07_1_4_1_fu_526_p3 <= 
        sum_V_4_2_fu_522_p2 when (tmp_30_reg_967(0) = '1') else 
        p_07_1_4_1_reg_961;
    sum_V_4_2_fu_522_p2 <= std_logic_vector(unsigned(track_2_hwPt_V_read_1_reg_828) + unsigned(p_07_1_4_1_reg_961));
    sum_V_4_3_fu_572_p2 <= std_logic_vector(unsigned(track_3_hwPt_V_read_1_reg_819) + unsigned(sum_V_4_2_07_1_4_1_reg_1016));
    sum_V_4_4_07_1_4_3_fu_626_p3 <= 
        sum_V_4_4_fu_622_p2 when (ap_pipeline_reg_pp0_iter1_tmp_32_reg_977(0) = '1') else 
        p_07_1_4_3_reg_1046;
    sum_V_4_4_fu_622_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter1_track_4_hwPt_V_read_1_reg_810) + unsigned(p_07_1_4_3_reg_1046));
    sum_V_4_5_fu_672_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter1_track_5_hwPt_V_read_1_reg_801) + unsigned(sum_V_4_4_07_1_4_3_reg_1076));
    sum_V_4_6_fu_722_p2 <= std_logic_vector(unsigned(ap_pipeline_reg_pp0_iter2_track_6_hwPt_V_read_1_reg_792) + unsigned(p_07_1_4_5_reg_1106));
    sumtk_0_V_write_ass_fu_686_p3 <= 
        sum_V_0_6_fu_682_p2 when (ap_pipeline_reg_pp0_iter2_tmp_6_reg_863(0) = '1') else 
        p_07_1_0_5_reg_1082;
    sumtk_1_V_write_ass_fu_696_p3 <= 
        sum_V_1_6_fu_692_p2 when (ap_pipeline_reg_pp0_iter2_tmp_13_reg_894(0) = '1') else 
        sum_V_1_5_07_1_1_4_reg_1088;
    sumtk_2_V_write_ass_fu_706_p3 <= 
        sum_V_2_6_fu_702_p2 when (ap_pipeline_reg_pp0_iter2_tmp_20_reg_925(0) = '1') else 
        p_07_1_2_5_reg_1094;
    sumtk_3_V_write_ass_fu_716_p3 <= 
        sum_V_3_6_fu_712_p2 when (ap_pipeline_reg_pp0_iter2_tmp_27_reg_956(0) = '1') else 
        sum_V_3_5_07_1_3_4_reg_1100;
    sumtk_4_V_write_ass_fu_726_p3 <= 
        sum_V_4_6_fu_722_p2 when (ap_pipeline_reg_pp0_iter2_tmp_34_reg_987(0) = '1') else 
        p_07_1_4_5_reg_1106;
    tmp_14_fu_158_p3 <= calo_track_link_bit_s(2 downto 2);
    tmp_15_fu_302_p3 <= ap_port_reg_calo_track_link_bit_7(2 downto 2);
    tmp_1_fu_206_p1 <= ap_port_reg_calo_track_link_bit_7(1 - 1 downto 0);
    tmp_21_fu_174_p3 <= calo_track_link_bit_s(3 downto 3);
    tmp_22_fu_362_p3 <= ap_port_reg_calo_track_link_bit_7(3 downto 3);
    tmp_28_fu_190_p3 <= calo_track_link_bit_s(4 downto 4);
    tmp_29_fu_422_p3 <= ap_port_reg_calo_track_link_bit_7(4 downto 4);
    tmp_2_fu_222_p1 <= ap_port_reg_calo_track_link_bit_8(1 - 1 downto 0);
    tmp_3_fu_226_p1 <= ap_port_reg_calo_track_link_bit_9(1 - 1 downto 0);
    tmp_4_fu_230_p1 <= ap_port_reg_calo_track_link_bit_10(1 - 1 downto 0);
    tmp_5_fu_234_p1 <= ap_port_reg_calo_track_link_bit_11(1 - 1 downto 0);
    tmp_6_fu_238_p1 <= ap_port_reg_calo_track_link_bit_12(1 - 1 downto 0);
    tmp_7_fu_142_p3 <= calo_track_link_bit_s(1 downto 1);
    tmp_8_fu_242_p3 <= ap_port_reg_calo_track_link_bit_7(1 downto 1);
    tmp_fu_130_p1 <= calo_track_link_bit_s(1 - 1 downto 0);
    track_0_hwPt_V_read_1_fu_150_p3 <= 
        track_0_hwPt_V_read when (tmp_7_fu_142_p3(0) = '1') else 
        ap_const_lv16_0;
    track_0_hwPt_V_read_2_fu_182_p3 <= 
        track_0_hwPt_V_read when (tmp_21_fu_174_p3(0) = '1') else 
        ap_const_lv16_0;
end behav;
